### ISSUE TITLE
Libanswers Plugin Throwing JS Error

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#224]
ReferenceError: springSpace is not defined @ 
api2.libanswers.com/js2.18.5/LibAnswers_widget.min.js:3

It does not appear to have any side effects, but should be resolved.

@danfox01 FYI

**Comment by martypowell** [comment]
@danfox01 I think we might need to contact the vendor about this one.

**Comment by martypowell** [comment]
@danfox01 I emailed you the details to send to the vendor. Assigning to you.

**Comment by mxsnyder** [comment]
Per discussion with Dan, we're removing from the release unit this can actually be worked on.

**Comment by danfox01** [comment]
Finally contacted LibAnswers about this. @martypowell, will let you know what they say.

**Comment by martypowell** [comment]
@danfox01 I think the error has changed slightly now.

![image](https://user-images.githubusercontent.com/1933400/40656301-0b4583f4-6312-11e8-9072-bdb3bae8dbc2.png)

To view the current errors, simply inpsect in chrome and view the console.

**Comment by martypowell** [comment]
@danfox01 this is ready for the next release.

**Comment by martypowell** [comment]
@danfox01 this no longer shows up in the bcpl pages. 🙌

**Comment by danfox01** [comment]
Yes!
