### ISSUE TITLE
Previous Blog Button Hiding instead of moving below the post list

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#243]
https://www.bcpl.info/blog

button on the left is hidden on smaller devices, but this is not the intended behavior

**Comment by mxsnyder** [comment]
@martypowell Do you mean "return to previous page"?

**Comment by martypowell** [comment]
@danfox01 I gave this some thought on a mobile device do we really care if this is visible? I would assume most users would either swipe if their browser supports that or use the back button which is available on android devices?

**Comment by danfox01** [comment]
Agreed. It’s mostly just to fill empty space on desktop.

**Comment by martypowell** [comment]
@danfox01 feel free to close this then.

**Comment by smarston** [comment]
Dan said yes, close it. 😁
