### ISSUE TITLE
Events Page Keyword Search Usability

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#245]
Basically the user has no clue that something is happenign when for example you type in a keyword on a mobile device.

**Comment by mxsnyder** [comment]
More info - in this example, as you search, you won't know you search completed. Since it's a live search, we can't just scroll down when the results populate. What if we display an "Event list updated!" message under the search box that fades after a second or two?

![image](https://user-images.githubusercontent.com/24256320/38954096-c6491c1a-431e-11e8-81bc-e93b3949b937.png)

**Comment by sdurphy** [comment]
@mxsnyder could we add a button to the fade in that would actually scroll you down to the list if pressed? 
![screen shot 2018-04-19 at 11 10 17 am](https://user-images.githubusercontent.com/2189638/39000555-4f7bd538-43c2-11e8-8b56-949996af9e12.png)

**Comment by mxsnyder** [comment]
I like it. Sure, we can do that.

**Comment by martypowell** [comment]
@sdurphy do we have a mockup for when the control is collapsed?

**Comment by sdurphy** [comment]
wouldn't it be this?:
![38954096-c6491c1a-431e-11e8-81bc-e93b3949b937](https://user-images.githubusercontent.com/2189638/39015247-c7a55e4e-43ea-11e8-8550-3a71cfa967c5.png)

**Comment by danfox01** [comment]
Sorry, late to the party. I like this. What is the reason for placing it under the input instead of using the standard purple window shade?

**Comment by martypowell** [comment]
just so everyone is in the loop, the filter box needs to be expandable on mobile, intially collapsed @sdurphy the man is going to give me something to work with

**Comment by sdurphy** [comment]
@martypowell - see attached

@danfox01 - what do you think about "Filter Events"?
![screen shot 2018-04-19 at 4 29 08 pm](https://user-images.githubusercontent.com/2189638/39016539-b9949438-43ee-11e8-817f-9dc9710a6a0b.png)

**Comment by danfox01** [comment]
I think that works great. I would like the button to be a bit taller, and I think the plus icon should be larger.

This should be the default behavior for all of our filters on mobile — databases, locations and events.

**Comment by martypowell** [comment]
@mxsnyder @danfox01 this in testing and is the reason its moved to on hold

**Comment by mxsnyder** [comment]
Renamed the "on hold" column "blocked" and moved this back in "in progress".

**Comment by danfox01** [comment]
@martypowell, Jason did finish. The only major issue he found was #371, but that was not a result of your change.

I also found one other layout issue unrelated to your change that I'd like to fix if possible -- #376.

**Comment by martypowell** [comment]
@danfox01 I will submit a pr for this, and work on the others independently.

**Comment by martypowell** [comment]
pr #378 submitted

**Comment by danfox01** [comment]
@martypowell I just noticed that the windowshade is also triggered when click an event and go to the details screen. That shouldn't happen. Let me know if that should be logged a separate issue.

**Comment by martypowell** [comment]
@danfox01 i think this is ready, but i can't check dev at the moment.

**Comment by martypowell** [comment]
@danfox01 this is ready for another look
