### ISSUE TITLE
Ancestry Database Destination Has Bad Link

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#254]
Back button 
https://catalog.bcpl.lib.md.us/polaris/message.aspx?ctx=1.1033.0.0.6

This should just return the user to the [databases ](https://www.bcpl.info/books-and-more/databases.html)page.

**Comment by mxsnyder** [comment]
I'm just setting it to do a `onclick="window.history.back(); return false;"` type of thing.

**Comment by mxsnyder** [comment]
Files to deploy: 
- message.aspx
