### ISSUE TITLE
Add This Popup not displaying like the Site Executive Version

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#261]
Site executive version opens up a modal when clicked and shows a menu when hovered. Polaris' version only shows menu when clicked and no modal

**Comment by mxsnyder** [comment]
Per @danfox01 I'm removing the share link.

**Comment by mxsnyder** [comment]
Files to deploy:
- site.master
- search/usercontrols/ctrlTitle.ascx
