### ISSUE TITLE
Invalid event date for week-long event

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#262]
Load next 10 events a three times, then just after Wednesday, April 25, Comes Wednesday, December 31, 1969 and under the clock it says “bad start time” When I click on the link to the program, it’s a week long thing. Proably messing with the programming code?

https://staging.bcpl.info/events-and-programs/list.html#!/?term=bcreads

**Comment by martypowell** [comment]
assigning to @danfox01, we need feedback on whether or not we need to display a date for ongoing events

**Comment by danfox01** [comment]
@martypowell do you mean display date or display time? We need to display date, not time. According to Samantha, ongiong is just a checkbox option in Evanced, and does not allow setting a time once selected.

**Comment by martypowell** [comment]
@danfox01 i meant time, sorry.

**Comment by martypowell** [comment]
Fixed by #279
