### ISSUE TITLE
Polaris mobile breakpoints don't match website breakpoints

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#268]
Specifically on my iPhone 7, landscape renders polaris in a two-column view more suitable for tablet then phone.

**Comment by mxsnyder** [comment]
Files to deploy:
- site.master
- css files

**Comment by danfox01** [comment]
Found another page that's affected by this. Please see full display for a title at mobile landscape size. It prob shouldn't render two columns until >768px.

Ex: https://catalog.bcpl.lib.md.us/polaris/search/title.aspx?ctx=1.1033.0.0.6&cn=764291
