### ISSUE TITLE
Truncate super-long Polaris title summaries in search results

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#272]
Is it possible to limit the length on these in any way? Even if it's just a hard stop after a certain number of characters it would be better then some of these...

https://catalog.bcpl.lib.md.us/polaris/search/searchresults.aspx?ctx=1.1033.0.0.6&type=Keyword&term=Flying%20Lessons%20%26%20Other%20Stories&by=KW&sort=MP&limit=TOM=aeb&query=&page=0&searchid=17

**Comment by danfox01** [comment]
This might need fine tuning, but let's truncate the summary at 100 words for now. That will eliminate the really egregious ones.

**Comment by mxsnyder** [comment]
Check out https://www.baltimorecountymd.gov/News/PoliceNews/PoliceTV/policereport.html

**Comment by danfox01** [comment]
@mxsnyder, what am I looking at on that page?

**Comment by mxsnyder** [comment]
@danfox01 Apologies, that was a note to self.

**Comment by mxsnyder** [comment]
I want to discuss with @martypowell before taking this on.

**Comment by danfox01** [comment]
Per conversation with @mxsnyder, let's do a character count of 500.

**Comment by mxsnyder** [comment]
Cool - check it out
https://ils-test.bcpl.lib.md.us/polaris/view.aspx?keyword=harry%20potter

**Comment by danfox01** [comment]
Perfect.

**Comment by mxsnyder** [comment]
Great! I also added the truncation tool to the main site, so it can be used there. 

Submitting PR

**Comment by mxsnyder** [comment]
File list:
- site.master
- search/components/ajaxResults.aspx
- scripts/bcpl/truncator.js
