### ISSUE TITLE
Add the day of the week to individual Calendar events

### ISSUE THREAD

**Issue by sdurphy** [baltimorecounty/BCPL-assets#273]
It would be nice if the day of the week was included with the date in the table that displays below the description of the event.

**Comment by mxsnyder** [comment]
I'll take care of this while I'm in #338

**Comment by mxsnyder** [comment]
Normal event's details:

![image](https://user-images.githubusercontent.com/24256320/38946104-76163d44-4306-11e8-97c9-c5febae1b549.png)

Ongoing event's details:

![image](https://user-images.githubusercontent.com/24256320/38946134-8d80616c-4306-11e8-9a22-42e9a8cb1cb2.png)

**Comment by mxsnyder** [comment]
@sdurphy see the screenshots above, or look at these:
- https://dev.bcpl.info/events-and-programs/list.html#!/133793
- https://dev.bcpl.info/events-and-programs/list.html#!/151972

**Comment by mxsnyder** [comment]
@sdurphy This is now ready to be verified in production and closed out.

**Comment by sdurphy** [comment]
Verified in production. Thanks Mike
