### ISSUE TITLE
Book cover grid should items should align consistently

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#275]
Currently, book covers displayed in a grid become misalinged and inconsistent when the covers aren't all the same size. Need a way to ensure grids look more consistently griddy.

Example: https://www.bcpl.info/blog/2018/new-next-week

**Comment by mxsnyder** [comment]
Assigning to Dan to close out.

**Comment by danfox01** [comment]
Gorgeous!
