### ISSUE TITLE
Reduce SVG logo size in Polaris to match SE version

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#277]
Compare:

- https://www.bcpl.info/
- https://catalog.bcpl.lib.md.us/polaris/

**Comment by mxsnyder** [comment]
I'm comparing, but I don't see the difference.

**Comment by mxsnyder** [comment]
@danfox01 clarified this is an issue on mobile.

**Comment by mxsnyder** [comment]
Done in ILS-TEST.

Files to deploy:
- site.master
- css files

**Comment by danfox01** [comment]
There's still some difference between these at sizes <768. Polaris version has image background while site is solid green, and Polaris has more height.

**Comment by mxsnyder** [comment]
@danfox01 to clarify, the issue now is the header background, and the height of the header, but the logo is good to go, correct?

**Comment by danfox01** [comment]
Correct, the logo itself if good, but the background and height of the header are different from the SE header.

Sorry, didn't realize there were two separate issues. I can open a new issue if needed.

**Comment by mxsnyder** [comment]
"Yep" - @danfox01
