### ISSUE TITLE
Polaris Items Out screen is cut off in all browsers

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#288]
I have not verified but the customer reports: When looking at “Items Out” in your Account, the right side of the screen is cut off.

@mxsnyder thinks this is related to the table display on that page.

**Comment by mxsnyder** [comment]
Assigned Dan for feedback of we're going to do the 2-column model on small screens.

**Comment by danfox01** [comment]
@mxsnyder related to this table, do we have any control over the order of these columns in Polaris admin or elsewhere?

**Comment by danfox01** [comment]
This was already reported via another issue from BCPL -- in which any account screen that includes a table is very difficult to use on mobile. @mxsnyder, please advise whether a new issue should be opened, or this one repurposed to expand the scope of this from a bug to en enhancement.

**Comment by mxsnyder** [comment]
@danfox01 We can expand scope, since the fix will apply to all tables. I just need clarification on whether or not we're using the 2-column model I proposed.

![image](https://user-images.githubusercontent.com/24256320/38686717-fd5a842c-3e42-11e8-81c7-267b3eeafab1.png)

**Comment by mxsnyder** [comment]
Leaving this in triage for now.

**Comment by mxsnyder** [comment]
This can be done, but it's a code change. It'll take about 5 minutes; just let me know what order you want them in.

![image](https://user-images.githubusercontent.com/24256320/38736187-439e0998-3ef9-11e8-8709-39361d15f370.png)

**Comment by mxsnyder** [comment]
@danfox01 Sure thing. Moving to "to do".

**Comment by mxsnyder** [comment]
Before:

![image](https://user-images.githubusercontent.com/24256320/38822694-35a439a4-4172-11e8-86dd-ad8fbf4332f1.png)

After:

![image](https://user-images.githubusercontent.com/24256320/38822717-4a521dc6-4172-11e8-965b-19ce294bf2e5.png)

**Comment by mxsnyder** [comment]
Added "details" heading to mobile view:

![image](https://user-images.githubusercontent.com/24256320/38822816-9417dd60-4172-11e8-8c0b-e13973870f6d.png)

**Comment by mxsnyder** [comment]
Submitted PR

**Comment by danfox01** [comment]
I like it. What does the i icon do?

**Comment by mxsnyder** [comment]
The "i" icon brings up a modal with details:

![image](https://user-images.githubusercontent.com/24256320/38824222-8dd626e2-4176-11e8-89ab-fdc78daa857b.png)

**Comment by danfox01** [comment]
Thanks. In that case, one change -- can we move Details to the end?

**Comment by mxsnyder** [comment]
Sure, I'll move this back to **in progress**.

**Comment by mxsnyder** [comment]
From email:

> Then yup, let's go ahead and do it. My goal when I set this up was to use one date input for everything, but this isn't too bad.

**Comment by mxsnyder** [comment]
Done!

![image](https://user-images.githubusercontent.com/24256320/38870905-396a3722-421d-11e8-839d-2aa83646ce41.png)

**Comment by danfox01** [comment]
Perfect.

**Comment by danfox01** [comment]
Looks good. I want to make a couple of tweaks if possible for next week. Will open a new issue.
