### ISSUE TITLE
Footer changes to make Adjust Contrast more prominent

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#290]
Can we make the following changes to mitigate feedback that the contraster is too hard to find?

- Increase font size of all gray footer elements to .9em (currently, text is .8em and translate is .75em)
- Increase size of toggle switch about 25%
- Make "Adjust Contrast" text a link that also triggers the toggle?

We might want to pump the text size of the footer promotions to .9 as well so they don't feel smaller than everything else. @sdurphy what do you think?

**Reminder: This needs to be fixed in SE and Polaris.**

**Comment by danfox01** [comment]
Actually, it looks like .**footer-copyright** and **.footer-copyright-nav** both have font-size: .8em applied... meaning that the nav items are actually being shrunk twice. Can we just take the .8em off of the nav class?

I'd like to still increase the size of the toggle slightly and make the text "Adjust Contrast" into a link.

**Comment by mxsnyder** [comment]
@danfox01 Check out https://dev.bcpl.info/index.html and let me know.

**Comment by danfox01** [comment]
Size looks great. Is it possible to linkify the adjust contrast text as well? That would make it a bigger target for someone who has low vision.

**Comment by sdurphy** [comment]
sorry about that... I hit close thinking it was save

**Comment by mxsnyder** [comment]
Linkify I shall.

**Comment by sdurphy** [comment]
Thanks Yoda

**Comment by mxsnyder** [comment]
Linkified, it is.

https://dev.bcpl.info/index.html

Note: I did all of this to Polaris too, but you won't see it in dev since it's pointed at the production JS. I did temporarily point it to the dev JS, and it worked splendidly.

**Comment by mxsnyder** [comment]
Files to deploy:
- site.master
- css files

**Comment by mxsnyder** [comment]
PRs submitted

**Comment by mxsnyder** [comment]
@danfox01 Please verify and close out.

**Comment by danfox01** [comment]
Verified.
