### ISSUE TITLE
Button text size should be 1em

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#291]
I am almost positive these used to be larger, but button text is currently 14px for the btn/btn-primary class. It should be 1em to match other body content.

**Comment by danfox01** [comment]
Actually, looks like some buttons are assigned **btn btn-primary** and others are assigned just **btn-primary.** The 14px size is coming from the btn class.

**Comment by martypowell** [comment]
@danfox01 see below for a 1em button, let me know if that's what you desire

![image](https://user-images.githubusercontent.com/1933400/38877767-6ec2b9ca-422d-11e8-90f1-3545ab379417.png)

**Comment by danfox01** [comment]
Since my discovery about size differences between btn and btn-primary being the actual cause of this, I need to think about it a bit more. Can we move this to next week?

**Comment by martypowell** [comment]
@danfox01 moving this to next week.

**Comment by danfox01** [comment]
@martypowell I think this is OK as is. At least for now. I will remove from this release unless you have an objection. Bigger fish to fry.

**Comment by martypowell** [comment]
@danfox01 sounds good to me.

**Comment by smarston** [comment]
Dan changed his mind. :(
