### ISSUE TITLE
Add Polaris autocomplete to global search box

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#292]
I believe @martypowell is already looking into this.

The global catalog search in the site header should include the same autocomplete that appears on the main catalog page: http://catalog.bcpl.lib.md.us/polaris/

I think we previously determined this could be done via the Polaris API.

**Comment by danfox01** [comment]
This looks great in dev. Two small changes:

- The selected search term disappears from the input box when you hit enter. Can we get it to stick around?

- There is extra space between the bottom of the autocomplete and the bottom of the transparent container. Can the space be made to match the left and right borders?

**Comment by martypowell** [comment]
@danfox01 on it.

**Comment by martypowell** [comment]
Fixed with #315
