### ISSUE TITLE
Remove extra padding on title detail view on mobile

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#293]
A few of the "c-title-detail" containers have a few ems of right padding that is making the table too narrow.

https://catalog.bcpl.lib.md.us/polaris/search/title.aspx?ctx=1.1033.0.0.6&cn=764291

**Comment by martypowell** [comment]
@danfox01 @mxsnyder do you mind adding a screenshot and pointing out the desired padding to be removed?

**Comment by martypowell** [comment]
spoke with @mxsnyder , we are going to wait until @danfox01 returns on wednesday to get this look right. It will not be a big change and will only take a couple of minutes to get ready for release.

**Comment by mxsnyder** [comment]
On hold for @danfox01

**Comment by danfox01** [comment]
@mxsnyder and @martypowell let me know if this is enough information.

First observe the following:

1. Go to: https://catalog.bcpl.lib.md.us/polaris/search/title.aspx?ctx=1.1033.0.0.6&cn=764291
1. Click "More" to reveal full details.
1. Size the screen to just **above** 500px wide and note the amount of padding on the left.
1. Size the screen down to under 500px and see that the left padding increases.

With all that in mind, I think we need two things:

Below 500px, the left padding should be the same as what it is when viewed just over 500px. It shouldn't increase as the screen gets smaller.

The padding on the right should match what's on the left -- right now there are multiple nested containers that are adding additional ems of right padding at small sizes.

**Comment by martypowell** [comment]
talked to @danfox01 , i'm a little nervous about pushing this one tonight, we are pushing to next week.

@mxsnyder

**Comment by danfox01** [comment]
Let's talk about this one soonish. @martypowell had some concerns about the implications of this change elsewhere in Polaris. It's not critical, so if the risk outweighs the benefit, we can shelve it.

**Comment by danfox01** [comment]
Moving this to next week.

**Comment by martypowell** [comment]
https://catalog.bcpl.lib.md.us/polaris/rss/whatis.aspx

**Comment by martypowell** [comment]
@danfox01 in dev, pending code review

**Comment by danfox01** [comment]
Implemented in 1.4
