### ISSUE TITLE
Place labels above content in Polaris results on mobile

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#294]
In Polaris search results, all of the labels and details are aligned horizontally on mobile, but vertical would be better on small screens. I was able to edit this in the inspector by changing that div to display:block and width: 100%, but you might have a better way. See screen shots below. I also reduced the padding around the entire container as well so squeeze out a little more space for content

**Current:**
![fireshot capture 023 - baltimore county public library_ - https___catalog bcpl lib md us_pol](https://user-images.githubusercontent.com/13049389/38459113-bcf7aa54-3a73-11e8-9469-a125aae0f93c.png)

**To Be:**
![fireshot capture 022 - baltimore county public library_ - https___catalog bcpl lib md us_pol](https://user-images.githubusercontent.com/13049389/38459102-9d4e77be-3a73-11e8-94ed-27ce06703928.png)

**Comment by mxsnyder** [comment]
@danfox01 How's this look? 

https://ils-test.bcpl.lib.md.us/polaris/view.aspx?keyword=harry%20potter

**Comment by danfox01** [comment]
Still kinda funky on XS screens. Is it the width of the element?

**Comment by mxsnyder** [comment]
Oops, a last-minute change didn't make it in. Ready for another look.

**Comment by mxsnyder** [comment]
Per @danfox01 via hangouts, this looks good.

**Comment by mxsnyder** [comment]
Files to deploy:
- css files

**Comment by mxsnyder** [comment]
@danfox01 Please verify and close out.
