### ISSUE TITLE
Upcoming events feed items should stack on small screens

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#296]
Currently display side by side, but they should stack vertically like the homepage.

Example: https://www.bcpl.info/locations/arbutus/index.html

![fireshot capture 066 - arbutus - https___www bcpl info_locations_arbutus_index html](https://user-images.githubusercontent.com/13049389/38512599-a0a4c6fc-3bf9-11e8-83b2-1ad64b107f72.png)

**Comment by mxsnyder** [comment]
#279 will address
