### ISSUE TITLE
Polaris mobile breakpoints don't match website breakpoints (part 2)

### ISSUE THREAD

**Issue by mxsnyder** [baltimorecounty/BCPL-assets#298]
Specifically on my iPhone 7, landscape renders polaris in a two-column view more suitable for tablet then phone.

Found another page that's affected by this. Please see full display for a title at mobile landscape size. It prob shouldn't render two columns until >768px.

Ex: https://catalog.bcpl.lib.md.us/polaris/search/title.aspx?ctx=1.1033.0.0.6&cn=764291

**Comment by martypowell** [comment]
@danfox01 I can't seem to recreate this anymore, are you able to?

**Comment by mxsnyder** [comment]
On hold for @danfox01

**Comment by martypowell** [comment]
@danfox01 i've attempted to fix this on ils-test, can you take a look? If it looks good, can you have Jason or Michael bang around on it, the style updates are somewhat generic and i just want to make sure I didn't eff anything up.

**Comment by danfox01** [comment]
Sorry, just getting to this. Doesn't seem to be resolved in ils-test. We can pull it from this week's release and address next week.

**Comment by danfox01** [comment]
Confirmed resolved in release 1.2.0
