### ISSUE TITLE
Broken link on renewal reminder

### ISSUE THREAD

**Issue by jeffreytompkins** [baltimorecounty/BCPL-assets#300]
I got an email and text message telling me that books were due soon.  They referred to link www.bcpl.info/go/account - forwarded the email to my baltimorecountymd.gov email - where the link was then expanded (see below) - but if I just try https://www.bcpl.info/error.html I get 404 (same with http).

**Forwarded email text:**
From: <notice@bcpl.net>
Date: Sun, Apr 8, 2018, 8:18 AM
Subject: A reminder from your library
To: <jeffrey.tompkins@verizon.net>, <jeffro.tompkins@gmail.com>

				
From:
Towson Branch
320 York Road
TOWSON, MD 21204
410-887-6166

To:
Jeffrey William Tompkins 
342 Rossiter Avenue
Baltimore, MD 21221
				
A REMINDER: The following items are due back to the library on the dates indicated. If these are ebooks or e-audiobooks, you don't need to do anything, as downloaded items will automatically expire on the due date. Items with pending hold requests may not be available for renewals.

For further information about your library account, please visit http://secure-web.cisco.com/1gDfQKYX-dv0AQTiqJIemm5FFfUHheU-DbAKi3lWo4sxIBWqQnsHM0p10U1aWmUlImua2lylIirF5m1DvQibNMm62DLvfE7lhCHo9_qOMAbh3PhLY0GxING1iUV2m2y91CA0qgDJEe0VaGOnSCN8pAaiFMzpjnCpbVygBdFmYXRpFqD09jtYPf2WEzGc3-aRCoSam2h7hWL45aSwKD4rVOs_mAvtO0rUGkFV5NT9GWOtrCYKvlNgOX_7v-LJ8P3iRg2wtREs0AT4gunBhmY8r0yCBYmc6Yoyx8AUXY5tW6g1Q__GrYqAQTr7OTzNXuewVEd4Gmd7AZg6XACn28By2lDrT1-Ehjdv9rA9GRmdaWoDmczDHLDj2t6YolRVog8NVsVrpmftGAzdgVFZEAhlsrBp4hRLymA7U7-cJldVyT_XuqbnkymMV0xCPGGQFFD_GyKylL-CFjPoSu_qbXxWLuA/http%3A%2F%2Fwww.bcpl.info%2Fgo%2Faccount or call our Shelf Help line at 410-494-9063. 

We offer text message notification! Please see a branch staff member for more details.
Due Date	Title	Format	From	Renewals remaining
4/11/2018	Donny's inferno	Book	Towson Branch	1
4/11/2018	Odd and the Frost Giants	Book	Towson Branch	1
4/11/2018	The sword in the stone	Book	Towson Branch	1
4/11/2018	It's like this, cat.	Book	Towson Branch	1
4/11/2018	Blastin' the blues	Book	Towson Branch	1
4/11/2018	Glory be	Book	Towson Branch	1
4/11/2018	Railway children.	Book	Towson Branch	1
4/11/2018	The amazing stitching handbook for kids : 17 embroidery stitches :15 fun & easy projects	Book	Towson Branch	1

**Comment by danfox01** [comment]
Found this in the language editor. I will redirect it.

**Comment by danfox01** [comment]
@jeffreytompkins, can you try the link again?

**Comment by danfox01** [comment]
Resolved by SE redirect.
