### ISSUE TITLE
Header for Polaris should match header for site

### ISSUE THREAD

**Issue by mxsnyder** [baltimorecounty/BCPL-assets#301]
![image-1](https://user-images.githubusercontent.com/24256320/38558928-abc637ae-3c9f-11e8-8ecc-756093ea1fb7.jpg)

**Comment by martypowell** [comment]
@mxsnyder I believe this was resolved with #315 , can you please confirm?

**Comment by martypowell** [comment]
@mxsnyder look at production.

**Comment by mxsnyder** [comment]
@martypowell I stand corrected.
