### ISSUE TITLE
Events should display a conditional disclaimer for certain age groups

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#305]
For the following age groups:

- Baby
- Toddler
- Preschool
- Elementary School Age

The following text needs to be added to the card, detail and registration screen:

Children under 8 must be accompanied by adult.

On detail and registration screens it can just be appended to the end of the description. We will need a design for the card layout though.

---
File list:
- dist/js/apps/events-page/app.js
- dist/js/apps/events-page/templates/eventList.html
- dist/js/apps/events-page/partials/eventDetails.html
- dist/js/apps/events-page/partials/eventRegistration.html

**Comment by mxsnyder** [comment]
Sam, thoughts?

![image](https://user-images.githubusercontent.com/24256320/38949534-a8fb69a0-4310-11e8-9fac-2343cd7caba2.png)

**Comment by sdurphy** [comment]
I think this is fine. 

@danfox01 do you think we need the word "children" or do you think that silly people would think that if they drop off 9 kids they won't need to accompany them? lol

**Comment by mxsnyder** [comment]
@danfox01, please have a look. If you don't see any changes, let me know and I'll redeploy the branch.

https://dev.bcpl.info/events-and-programs/list.html#!/?ageGroups=Baby%20(0%20to%2023%20months),Toddler%20(2%20to%203%20years),Preschool%20(2%20to%205%20years),Elementary%20School%20Age%20(6%20to%2011%20years)&startDate=April%2023,%202018&endDate=May%2018,%202018

https://dev.bcpl.info/events-and-programs/list.html#!/129086

https://dev.bcpl.info/events-and-programs/list.html#!/register/129086

**Comment by danfox01** [comment]
The only change I have for now is that the disclaimer should be in the same place on both the detail page and registration page. Right now the placement is good for the detail page, but if you select register, the disclaimer jumps up above the description.

**Comment by mxsnyder** [comment]
I've made your dreams come true:

https://dev.bcpl.info/events-and-programs/list.html#!/register/129086

**Comment by danfox01** [comment]
Hooray! Let's kill the period after "adult" to match the registration required label, and it's all good.

**Comment by danfox01** [comment]
Erm, also, can we reduce the space between the two alerts slightly? They seem a little too far apart compared to everything else

**Comment by danfox01** [comment]
@mxsnyder, can we kill the period after "adult" in the card disclaimer in time for this release?

**Comment by mxsnyder** [comment]
I think that won't be a problem. One sec.
