### ISSUE TITLE
Event registration button should be active as soon as user types a valid phone

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#309]
@martypowell and I identified this last week, but it's now been raised as an issue by BCPL.

**Current behavior:**

The submit button doesn't become active until after the user enters valid information in all four boxes. The validation doesn't occur until after the user changes focus, so it's not possible to type a phone and the immediatelly click submit.

**Expected behavior**

The user should be able to click the submit button immediately after entering a valid phone, without having to click elsewhere or tab out first.

**Comment by martypowell** [comment]
Since, I am familiar with this issue, I'll take a stab at it.

**Comment by martypowell** [comment]
@danfox01 mike confirmed this in dev, I moved to ready for release, but if you aren't happy with it, go ahead and move it back.

**Comment by danfox01** [comment]
Thanks, I'll take a look in dev on Wednesday morning. Meantime, can you please ask @smarston to set up a test event and have Jason run a test submission? Just a quick check to make sure phone validation still works as expected, submissions return proper success message, and that nothing else jumps out.

**Comment by martypowell** [comment]
@danfox01 done

**Comment by danfox01** [comment]
Found a bug, I believe:

- Click "submit" before filling out any fields.
- Loading indicator appears in button, and buttn becomes unclickable.
- Button remains unclickable even when all fields are filled out.

I think the button should remain clickable at all times, and re-run validation every time it's clicked. If all fields are valid, it should submit.

**Comment by martypowell** [comment]
@danfox01 confirmed, on it.

**Comment by martypowell** [comment]
@danfox01 ready for another look.

**Comment by danfox01** [comment]
Looks good to me. I will ask Samantha to create another test event and have Jason run through submission quickly.

**Comment by martypowell** [comment]
@danfox01 sounds good.

**Comment by mxsnyder** [comment]
Shouldn't have auto-closed.

**Comment by danfox01** [comment]
Jason confirmed submission worked. This looks good.

**Comment by danfox01** [comment]
Confirmed resolved in release 1.2.0
