### ISSUE TITLE
Sort blog by Start Date instead of Print Date

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#318]
Marty and I already discussed this pre-launch and deferred any action but BCPL has asked for this to be prioritized. Please not this is for the main blog view and NOT the homepage viewlet, which is displaying fine.

The problem is that SE structured content layouts sort by Print Date and not Start Date. You can see this in action at bcpl.info/blog. Older posts come first and the order is generally weird.

I am reopening a ticket with Systems, but is there any quick fix with JS that can reorder the content by _seStartDate when the page is rendered? I’m just looking to stop the bleeding on this one and implement a better fix later.

**Comment by danfox01** [comment]
@mxsnyder I believe this is what we agreed to to resole this issue:
 
1. Set up a Handlebars template for blog posts
2. Write the JS module to populate the handlebars template and call the blog’s json endpoint (https://www.bcpl.info/blog?format=json), and sort the posts.

The only catch is that the default structured content list page (currently at bcpl.info/blog) needs to remain the default landing page. Otherwise, I don't think the breadcrumb will continue to link properly.

**Comment by mxsnyder** [comment]
@danfox01 I just hit a snag -- the blog JSON only returns the upcoming 10 posts. That means as you page through the blog posts, it'll still be somewhat unsorted. We'll need to get in touch with SA and see what they recommend. I'll email them right now.

**Comment by mxsnyder** [comment]
Emailed SA support.

**Comment by mxsnyder** [comment]
Big thanks to @danfox01 for finding an old email that described exactly what to do.

1. Go into Modules/Applications > BCPL Blog > Fields > Edit "Content Date" and change the context to "required”
2. Apply the change to layout via Content Landing Page > Edit Layout > Source > Line 29 change content.get_startDate().value to content.get_printDate().value

Currently evaluating process changes.

**Comment by mxsnyder** [comment]
@danfox01 Done in production, and I set all of the blog post publish dates too.

**Comment by danfox01** [comment]
Thanks! Sort looks great but it looks like we lost all of the thumbnails, at least on mobile which is all I can see right now. Can you investigate?

**Comment by mxsnyder** [comment]
Sure, I'll open a new issue.
