### ISSUE TITLE
Polaris - New Books is Missing Content Area Styling

### ISSUE THREAD

**Issue by sdurphy** [baltimorecounty/BCPL-assets#320]
In Polaris the New Books page in the New Titles section is missing the styling for the content area.
Example: https://catalog.bcpl.lib.md.us/polaris/Search/newreleases.aspx?ListingTypeID=26&ctx=1.1033.0.0.6

**Comment by martypowell** [comment]
@sdurphy @danfox01 @mxsnyder this has been resolved on ils-test and confirmed by Sam.

**Comment by danfox01** [comment]
Confirmed resolved in release 1.2.0
