### ISSUE TITLE
Polaris - What's RSS is Missing Content Area Styling

### ISSUE THREAD

**Issue by sdurphy** [baltimorecounty/BCPL-assets#324]
Example: https://catalog.bcpl.lib.md.us/polaris/rss/whatis.aspx?

**Comment by martypowell** [comment]
@mxsnyder this is in polaris, any ideas?

**Comment by danfox01** [comment]
@sdurphy where did you find this link?

**Comment by martypowell** [comment]
Does this work?

![image](https://user-images.githubusercontent.com/1933400/39014283-f51a19c6-43e7-11e8-99cc-05f3f45c0e93.png)

**Comment by sdurphy** [comment]
Is it possible to get rid of that excessive space above "About RSS"?

**Comment by martypowell** [comment]
https://ils-test.bcpl.lib.md.us/polaris/rss/whatis.aspx

**Comment by sdurphy** [comment]
Looks good
