### ISSUE TITLE
Events page is loading very slowly

### ISSUE THREAD

**Issue by mxsnyder** [baltimorecounty/BCPL-assets#326]
Liz Burnett just reported the events page is loading extremely slowly.

**Comment by mxsnyder** [comment]
We're both on this. It seems that Evanced is having issues.

**Comment by mxsnyder** [comment]
From http://www.demcosoftware.com/support/

> Over this past weekend we had various issues occur with regards to slowness within access of the system along with authentication-based issues.  Our development team is working towards resolving these issues and get things back up to speed.
> 
> Currently, we do not have an all clear, but we are seeing improvements in speed along with authentication working in most cases.

**Comment by danfox01** [comment]
Good find. Can you make sure to pass this on to heather so she can inform BCPL too?

**Comment by mxsnyder** [comment]
@smarston has already sent in a ticket to Evanced, and alerted Heather. We're considering putting up an alert.

**Comment by mxsnyder** [comment]
Heather is writing up an alert now, which @smarston will put on the site.

**Comment by mxsnyder** [comment]
Events page is back! Closing out.
