### ISSUE TITLE
Alert banner description text wrapping below ! icon

### ISSUE THREAD

**Issue by smarston** [baltimorecounty/BCPL-assets#327]
When alert description text is longer than one line, it wraps beneath the ! icon and looks a little off.

![alert text wrapping issue](https://user-images.githubusercontent.com/30531942/38820760-bf3d7ee2-416c-11e8-96b0-b98b30496d0f.jpg)

**Comment by martypowell** [comment]
@danfox01 how to you want to handle this?

**Comment by mxsnyder** [comment]
Removed from release since this hasn't been prioritized yet. We can discuss tomorrow morning.

**Comment by mxsnyder** [comment]
HTML and CSS worked out here:
https://codepen.io/anon/pen/KRKJqM

**Comment by mxsnyder** [comment]
How about this? (emergency version)

![image](https://user-images.githubusercontent.com/24256320/38955944-1550edb0-4324-11e8-94f5-349a902d4dbf.png)

**Comment by mxsnyder** [comment]
(I fixed the "View All Alerts" not being uppercase after the screeny, btw)

**Comment by mxsnyder** [comment]
Single line version:

![image](https://user-images.githubusercontent.com/24256320/38956396-6ee26100-4325-11e8-9da0-52bad861b477.png)

**Comment by mxsnyder** [comment]
It's responsive too:

![image](https://user-images.githubusercontent.com/24256320/38994606-d99d8918-43b4-11e8-8e0a-713b21c7d0d1.png)

**Comment by mxsnyder** [comment]
Confirmed!

**Comment by danfox01** [comment]
I think this is all good.

**Comment by mxsnyder** [comment]
Just realize the exclamation icon on yellow is supposed to be light tan. Fixing now.

**Comment by mxsnyder** [comment]
To release, replace the content of the snippets in these two content items with the following:
- _inclusions > alerts > container-alerts
- _inclusions > alerts > container-alerts-homepage

```HTML
<script id="alerts-template" type="text/x-handlebars-template">
	<div class="alert-wrapper {{alertData.EmergencyClass}}">
		<div class="container alert-container" style="display: none;">
			<div class="row">
				<div class="col-md-12">
					<div class="message">
						<div>
							<i class="fa fa-exclamation-circle fa-2x"><span class="sr-only">Alerts</span></i>
						</div>
						<p>{{alertData.Description}}</p>
						<div class="controls">
							<a class="view-all-alerts" href="https://www.bcpl.info/alerts.html">
								<i class="fa fa-list fa-lg" aria-hidden="true"><span class="sr-only">View All Alerts</span></i>View All Alerts
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</script>
<div id="alerts-target"></div>
```

File list:
- master and high-contrast css
