### ISSUE TITLE
Website search (Swiftype) paging doesn't work

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#329]
To replicate:

- Run a website search for a term with many results -- for example, "book"
- Scroll to the bottom and click on page 2 or 3
- Page not found

**Comment by martypowell** [comment]
Confirmed.

Unrelated to this bug, but related to this control. These numbers should probably be made easier to select.

**Comment by martypowell** [comment]
@mxsnyder i'm on this.

**Comment by martypowell** [comment]
@danfox01 this is resolved in production. The issue was with the template which is an html snippet on the search results page. It wasn't properly generating the link href for the paging buttons.

FYI @mxsnyder

**Comment by mxsnyder** [comment]
Reopening for @danfox01 to verify and close out.

**Comment by danfox01** [comment]
Looks great.
