### ISSUE TITLE
Evaluate development work required for Twitter feed embed

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#330]
I know this can be as simple as dropping [embed code](https://dev.twitter.com/web/embedded-timelines) on the page, but does anything else need to happen -- adding to source control or our pattern library, etc.?

**Comment by martypowell** [comment]
@danfox01 I don't see why we would need anything in source control. It might be good to document our widget configuration somewhere in the wiki though.

@mxsnyder what do you think?

**Comment by mxsnyder** [comment]
@martypowell Correct -- as long as we document it, we should be fine.

**Comment by danfox01** [comment]
@sdurphy, I believe we can use Twitter's embed tool to define the basic attributes, and then consider that our standard. Can you create something you are happy with and share it here?

https://dev.twitter.com/web/embedded-timelines

**Comment by sdurphy** [comment]
I haven't found a way to set a max number of Tweets... In the example [here](https://dev.bcpl.info/test.html) the height is fixed, but then that creates the scroll, which i don't like on mobile. So I'm slightly happy. Mike/Marty if I remove the height, do you think we could do something fancy with js that would present the tweets with a "load next 10" button? (Like we do for events)

**Comment by danfox01** [comment]
Sam, did you try the tweet-limit parameter? https://dev.twitter.com/web/embedded-timelines/parameters

**Comment by mxsnyder** [comment]
Since this is not a development issue, does anyone object to me dropping it from the 4/25 release and closing it out?

**Comment by danfox01** [comment]
@mxsnyder We can remove from the project but I’m waiting for @sdurphy to answer my question before closing out...

**Comment by mxsnyder** [comment]
Removed!

**Comment by sdurphy** [comment]
Updated...https://dev.bcpl.info/test.html

The feed is in a div with the ".pull-image-left" class, and that is all within a snippet. The clear at the bottom of the page is to prevent the feed from poking out of the content area.

**Comment by danfox01** [comment]
@mxsnyder @martypowell Any semantic concern about using the pull-image-left class on a non-image element?

**Comment by sdurphy** [comment]
@mxsnyder .pull-left wouldn't work because it doesn't include the lovely margins we have in place.

**Comment by danfox01** [comment]
@sdurphy decided a layout and dropped the code snippet on a dev page, which would have been blown away in this morning's refresh.

The only remaining issue was @mxsnyder's recommendation that we use the .pull-left/.pull-right class for positioning, plus and additional class for proper padding. The padding class doesn't exist. Can you two work together to come up with something to satisfy that last requirement?

**Comment by mxsnyder** [comment]
Sure. If @sdurphy would be so kind as to document how much padding he wants, we can add something to the codebase.

**Comment by sdurphy** [comment]
yikes.... the test page was obliterated in this morning's refresh.

**Comment by sdurphy** [comment]
i can quickly create again. @mxsnyder the margins should be exactly the same as the ones for pull-image-left

**Comment by mxsnyder** [comment]
@sdurphy No problemo. Do you want one for the right side too?

**Comment by sdurphy** [comment]
@mxsnyder Yes, right should be, margin: 5px 0 20px 30px

**Comment by mxsnyder** [comment]
We can add something like this:

```CSS
.left-aside-padded {
    padding: 5px 30px 20px 0;
}

.right-aside-padded {
    padding: 5px 0 20px 30px;
}
```

**Comment by mxsnyder** [comment]
@sdurphy I applied `.left-aside-padded` to the Twitter thingy on https://dev.bcpl.info/test.html. Good to go?
