### ISSUE TITLE
Polaris Catalog Search Options Display an Empty White Box on Mobile

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#331]
![image](https://user-images.githubusercontent.com/1933400/38871529-22aac126-421f-11e8-9fd4-5896d7fbcbf2.png)

**Comment by danfox01** [comment]
Can we move the search options into the same box as the search input?

**Comment by martypowell** [comment]
I think so, but it would change the desktop view (note this is rough and could be adjusted a bit)

![image](https://user-images.githubusercontent.com/1933400/38872799-1fe9a7ce-4222-11e8-96a5-2966d9b26612.png)

**Comment by martypowell** [comment]
@danfox01 what about the text below that?

**Comment by danfox01** [comment]
No strong feelings either way on leaving where it is or moving into the box.

**Comment by martypowell** [comment]
For release 1.2.0 we will be removing the white space, the rest of the issue has been split into a new issue #340

**Comment by danfox01** [comment]
Confirmed resolves in release 1.2.0
