### ISSUE TITLE
Blog thumbnails are missing

### ISSUE THREAD

**Issue by mxsnyder** [baltimorecounty/BCPL-assets#332]
The blog thumbnails are missing since the blog posts were put in order by #318.

**Comment by martypowell** [comment]
Fixed in production. Editing the template in Site Executive Stripped out the images and therefore is the reason the images weren't showing.

**Comment by martypowell** [comment]
Instructions for the future can be found [here](https://github.com/baltimorecounty/BCPL-assets/wiki/Sort-Structured-Content-by-Date)
