### ISSUE TITLE
Events API returns Unpublished Events

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#334]
**Proposed Fix**: Update service to check for published = true

fyi @danfox01 @smarston

**Comment by mxsnyder** [comment]
@martypowell This is only on the event details page, correct?

**Comment by martypowell** [comment]
@mxsnyder no, it was showing up in the list as well.

**Comment by mxsnyder** [comment]
@martypowell Are you talking about the Test event you saw on my machine yesterday when you stopped by? That one wasn't unpublished.

**Comment by martypowell** [comment]
https://dev.bcpl.info/events-and-programs/list.html#!/151971

**Comment by mxsnyder** [comment]
Sure, but it doesn't show up in the list. I'm not saying we shouldn't fix this -- I just want to define the problem.

**Comment by martypowell** [comment]
After looking at the evanced api, im not even sure if it's on our side. Obviously we should do something about it on the details page.

**Comment by mxsnyder** [comment]
This page needs some work for when an event id is invalid. It can be fixed here.
https://dev.bcpl.info/events-and-programs/list.html#!/99999999999

**Comment by mxsnyder** [comment]
Deploy list:
- /dist/js/apps/events-page/app.js
- /dist/js/apps/events-page/partials/eventDetail.html

**Comment by mxsnyder** [comment]
Dan approved via IM.

PR submitted.
