### ISSUE TITLE
Renewing an item in Polaris leads to confirmation page without proper styling

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#343]
I'm pretty sure this existed before the change, but just noticed now. My test account is out of renewals so I will have to wait till morning to grab a screen shot.

**Comment by martypowell** [comment]
@danfox01 you'll have to show me this one, I am not familiar with renewals.

**Comment by mxsnyder** [comment]
How's this?

![image](https://user-images.githubusercontent.com/24256320/39064427-797ff51e-449c-11e8-848c-9840e6edef1b.png)

**Comment by mxsnyder** [comment]
(the refresh eContent button is a different part of the page, and I'm not really sure what do to about it)

**Comment by mxsnyder** [comment]
File list:
- patronaccount/itemsout.aspx

**Comment by danfox01** [comment]
Much better. I don't really care about the econtent button.
