### ISSUE TITLE
Document process for cache-busting Polaris

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#344]
In the 1.2 release, a hard refresh is required to see changes. Do we update query strings similar to SE, or is there another process?

**Comment by martypowell** [comment]
@danfox01 as part of the release process we will need to add a step. This step will involve updating the site.master file with the new query strings

**Comment by mxsnyder** [comment]
https://github.com/baltimorecounty/BCPL-assets/wiki/Cache-Busting-(Web-or-Polaris)

**Comment by martypowell** [comment]
Closing as I have reviewed the document and it looks good.
