### ISSUE TITLE
Polaris "no results" page needs styling

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#345]
Just needs to be wrapped in a white content box, and the bulletted items need to actually look like bullets.

https://catalog.bcpl.lib.md.us/polaris/search/searchresults.aspx?ctx=1.1033.0.0.6&type=Keyword&term=asdf&by=KW&sort=MP&limit=TOM=*&query=&page=0

**Comment by martypowell** [comment]
@danfox01 apparently we just didn't copy this over. It's ok on ils-test. While troubleshooting @danfox01 links are messed up on some pages. This issue is tracked here #361
