### ISSUE TITLE
Evaluate effort to change emergency alerts behavior and switch to JSON

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#349]
My original plan for the emergency banner was a drop-down of issue types that could be selected (e.g., holiday, weather closure, website downtime, etc.) and would automatically determine the sort order of the alert and the color of the banner. I **think** due to limitations with HTML scraping we instead opted for a few yes/no toggles for "Show in bar?" and "Is emergency?" to set the priority and color.

BCPL has asked for direct access to update alerts themselves and I have concerns that the yes/no options are too obscure for them. Now that we know we can output to JSON instead of scraping, does that change any of the limitations that we had before? What is the effort on making this switch?

**Comment by danfox01** [comment]
Cool. Would you have time to start on this before you go? At least lay the ground for a future release?

**Comment by mxsnyder** [comment]
Sure. Is that the full scope of the requirements? Just to switch from API to JSON? Or is the requirement to remove the yes/no's, and just make the dropdown work? Is there another compelling reason to switch to JSON? (I'm not trying to be difficult, I just want to make sure my eyes are on the correct prize)

**Comment by danfox01** [comment]
Yup -- switch to JSON and replace the yes/no's with a drop-down that handles the thinking for the user. Let me know if you have any concerns with that at the moment -- I can document the details for you first thing tomorrow.

Would this have any impact on the way the alerts are pulled into Polaris?

**Comment by mxsnyder** [comment]
Great point. If we switch to JSON, we'll have to set the rendering server to allow cross-origin calls, or they'll be blocked. I'll email Mr. Sheppard and see what he things. We may have to discuss with SystemsAlliance.

**Comment by danfox01** [comment]
Ok, yes please start with Shep and we’ll take it from there. At half a day it’s worth the squeeze but I don’t know about much more than that. Thanks!

**Comment by martypowell** [comment]
@mxsnyder could we use services.bcpl.info to consume the site executive structured content json and allow both site executive and polaris to hit it?

**Comment by mxsnyder** [comment]
I have the API work done for this and merged into the master branch. I can do the front-end after tonight's deploy, so, tomorrow.

**Comment by martypowell** [comment]
this is in production confirmed by @mxsnyder

**Comment by danfox01** [comment]
@martypowell, just to confirm: Before he left I believe Mike told me the API changes were in prod but the CSS/JS and XML changes would be deployed with 1.4 .We're accounting for those, right?

**Comment by martypowell** [comment]
@danfox01 correct, yes.
