### ISSUE TITLE
Active Ongoing Event Showing in the Wrong Place in the Event List

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#355]
This event, https://www.bcpl.info/events-and-programs/list.html#!/144618. Shows up here:

![image](https://user-images.githubusercontent.com/1933400/38998364-6a84c7fe-43bd-11e8-97ba-06c0fe662fc6.png)

It seems like this is an issue with the evanced api, as the results returned are in the order we suspect. @smarston confirmed we are not able to set a EventStart for Ongoing events.

@danfox01 we probably need to get in touch with the vendor, I can provide you with some request information to help them diagnose.

FYI @mxsnyder

**Comment by danfox01** [comment]
Can you break down the scope of the problem so I can evaluate? I'm not understanding what aspect of the API is causing this.

If we need to rely on the vendor to fix this, we can assume it won't be resolved. Not trying to be dramatic, but they're something like 1 for 7 on issue resolution with us. So if that is the case, we should determine what options we do have, even if that means hiding ongoing events or instructing users to enter them differently.

**Comment by mxsnyder** [comment]
@danfox01 I can answer this. The events returned from Evanced are sorted by EventStart. That property is null for ongoing events, so they're sorted to the bottom of the list.

The only idea I have (and it's not a great idea) is to pull down a big list of events, and then sort them ourselves in the BCPL API. Then we'd cache them, and display the cached versions. We'd just have to be mindful of how long (maximum) event changes should have until they show up in the list.

**Comment by danfox01** [comment]
I'm not saying we don't contact them. I'm just saying our backup plan is probably going to be our only plan. Their support is atrocious. Sometimes we don't even get a response.

**Comment by danfox01** [comment]
This has inspired me to make a list of all the stuff their API doesn't do and send it all to them.

**Comment by mxsnyder** [comment]
Per discussion with Dan, we're removing from the release unit this can actually be worked on.
