### ISSUE TITLE
BranchEmailSwitcher is injecting jQuery Improperly

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#356]
Since the form is loaded before jQuery is, there are problems. Therefore our script isn't the way we want it to be.

**Comment by martypowell** [comment]
Potential idea on how to fix

https://jsfiddle.net/gossh4gf/4/

**Comment by mxsnyder** [comment]
What about attaching to window.onload, which (i believe) fires after document.ready?
