### ISSUE TITLE
SE Housekeeping: In the homepage template, component-hero should be nested within container-home-header

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#359]
**component-hero** is no longer a part of **container-home-header**. At some point the content of component-hero was copied directly into the container. Can the original layout be restored?

**Comment by mxsnyder** [comment]
Yeah, this is actually pretty simple. 
1. update component-hero from container-home-header
1. publish component-hero
1. embed component-hero in container-home-header
1. publish container-home-header

**Comment by mxsnyder** [comment]
Discussed with Dan, I'm doing this first thing Monday morning.

**Comment by mxsnyder** [comment]
Done and done! To @danfox01 for Approval and to close out.

**Comment by danfox01** [comment]
Thanks!
