### ISSUE TITLE
Polaris - Tables under Working List section are missing content background.

### ISSUE THREAD

**Issue by sdurphy** [baltimorecounty/BCPL-assets#363]
To observe issue please do the following:
1. After searching for a book, add the book to your list, using the “Add to My List” button.
2. Once, it’s added, under the “Working List” menu on the left side of the page, select, “Show list details…”
3. You will be taken to the working list page. On this page, the availability table is missing the white content area background. (The table
![screen shot 2018-04-19 at 3 44 57 pm](https://user-images.githubusercontent.com/2189638/39014576-bcb0002c-43e8-11e8-82a1-c5c69132c72f.png)
 should look like the screenshot attached)

**Comment by mxsnyder** [comment]
Adding the `content-container` class to the table, and the `content-module` class to the parent `<div>` will result in this:

![image](https://user-images.githubusercontent.com/24256320/39269441-d1d639e6-48a0-11e8-9946-f834e39ab13c.png)

The margins could use some work, but this gets us 90% of the way to where we want to be. Another thought--should this table be full-width?

**Comment by martypowell** [comment]
@mxsnyder are you waiting for @sdurphy on this one?

**Comment by mxsnyder** [comment]
In fact I am waiting on @sdurphy.

**Comment by sdurphy** [comment]
@mxsnyder can we make full width?

**Comment by mxsnyder** [comment]
@sdurphy How's this?

![image](https://user-images.githubusercontent.com/24256320/39325092-5042330c-495f-11e8-9cae-bfba2e55ee05.png)

**Comment by mxsnyder** [comment]
Or should the table be a part of the "card" above it?

**Comment by mxsnyder** [comment]
Like so:

![image](https://user-images.githubusercontent.com/24256320/39325187-8f156ec8-495f-11e8-821a-df3923e8f725.png)

**Comment by sdurphy** [comment]
I didn't think we could add it to the card above... I totally prefer it as part of the card.

**Comment by sdurphy** [comment]
I NEED MORE PADDING AROUND THAT TABLE @mxsnyder 
![more-cowbell](https://user-images.githubusercontent.com/2189638/39325443-31cc2684-4960-11e8-899a-668c7c99d897.gif)

**Comment by mxsnyder** [comment]
@sdurphy Done and done. Please review on ILS-TEST.

**Comment by sdurphy** [comment]
perfect. thanks @mxsnyder

**Comment by mxsnyder** [comment]
![image](https://user-images.githubusercontent.com/24256320/39326883-55f41d38-4964-11e8-96b7-ace143cd5bc5.png)
