### ISSUE TITLE
Items Out Table Tweaks

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#364]
Per conversation with @mxsnyder this morning:

- The "Call Number" column should be hidden to save space in the table.
- The column widths should be adjusted if possible to allow more width for the title.

**Comment by mxsnyder** [comment]
I've removed "Call Number" but didn't adjust the column widths, per @danfox01.

**Comment by mxsnyder** [comment]
And, to make myself sound like a liar, I just adjusted the columns and they're much better now.

![image](https://user-images.githubusercontent.com/24256320/39016483-982da276-43ee-11e8-8c60-ed4706dd998e.png)

Submitting PR

**Comment by mxsnyder** [comment]
Verified in dev!
