### ISSUE TITLE
Tablenate the "Requests" table

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#365]
https://catalog.bcpl.lib.md.us/polaris/patronaccount/requests.aspx

- Just like Items Out, this table needs to be tablenated for mobile.
- Also, please move the Format and Details ("i") column to the end.

**Comment by mxsnyder** [comment]
On the case.

**Comment by mxsnyder** [comment]
Done in dev, submitting PR. @danfox01 please to be having a look.
