### ISSUE TITLE
Implement Swiftype filtering to web content pages from blog posts

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#368]
See #325 for background.

From @mxsnyder 

> I just went over this with Dan.
> 
> Site search from the header will only search site pages
>
> On the results page, you have the option of repeating your search for the blog via a button or something simple
>
> I recommend we use filtering rather than facets. Here's what we'd do:
> 
> 1. Add a `<meta property='st:type' content='blog' />` tag to the `<head> `of the blog pages.
> 1. Add a `<meta property='st:type' content='content' />` tag to the `<head> `of the non-blog pages.
> 1. Update the API to accept a `?filter=blog` or `?filter=content` argument to filter the results
> 1. Re-index
> 1. Add a button to the search results page to re-run the search for whichever search type it didn't do
> 1. ???
> 1. Profit
>
> All in all, I think this can be done in less than half a day.

**Comment by mxsnyder** [comment]
API work done, PR submitted.

**Comment by mxsnyder** [comment]
SE steps:
1. Copy the BCPL-internal-hub template as BCPL-blog
1. Add meta tag (see above) to the BCPL-blog template
1. Publish the BCPL-blog template
1. Switch the blog to the BCPL-blog template
1. Add content meta tags to the other templates

**Comment by mxsnyder** [comment]
I'll do the SE steps on Monday. Not that I don't like making production changes on a Friday afternoon...

**Comment by danfox01** [comment]
Great work.

**Comment by mxsnyder** [comment]
Tag format:
* `<meta class='swiftype' name='type' data-type='enum' content='[type value]' />`

Doing the SE steps now.

**Comment by mxsnyder** [comment]
SE steps completed.

@danfox01 would you kick off the reindex?

**Comment by danfox01** [comment]
Will do.

**Comment by mxsnyder** [comment]
API deployed to staging. I can continue my testing after the reindex is done.

**Comment by mxsnyder** [comment]
This isn't as straightforward as it initially appeared. I may have to contact Swiftype if I can't get this soon.

**Comment by mxsnyder** [comment]
API work is done - I'll work on the front-end stuff tomorrow.

**Comment by mxsnyder** [comment]
File list:
- BCPL API
- dist/js/master.min.js
- dist/js/page-specific/site-search-results.min.js
- mockups/handlebars-templates/search-results-template.html (needs to go in the snippet on `/search-results.html`)

**Comment by mxsnyder** [comment]
@danfox01 approved over IM

**Comment by danfox01** [comment]
Look great. Two questions:

- This will apply to searches originating from the Polaris version of the header as well?
- Not for now, but I assume that changing the look of the "search our blog/search out site" link is an fairly easy? For example, if we wanted to make it more cohesive with the existing "search the catalog instead" button?

If the answer to both of those is yes, this is good to go.

**Comment by martypowell** [comment]
@mxsnyder moved this back into in progress dues to @danfox01 's pending question.

**Comment by mxsnyder** [comment]
- Regarding Polaris -- it should default to a content search if there are no search parameters, but I'll verify.
- Regarding the link -- yep, very easy to change. That code is in a snippet.

**Comment by mxsnyder** [comment]
Good call about Polaris. I just submitted #388 to default a lack of filters to be a content filter.
