### ISSUE TITLE
Links in SE don't take bold styling

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#369]
It seems that the font weight of an <a> tag is taking precedence over the weight of a strong tag. So, essentially, you can't make a link bold in the SE wizzy.

Example -- all the links on this page have strong applied:
https://dev.bcpl.info/_style-library/collections-df.html

**Comment by mxsnyder** [comment]
@danfox01 https://dev.bcpl.info/_style-library/collections-df.html

**Comment by danfox01** [comment]
That does it.

**Comment by mxsnyder** [comment]
PR submitted

**Comment by mxsnyder** [comment]
Moved to r4r.

**Comment by danfox01** [comment]
Resolved with Release 1.3
