### ISSUE TITLE
Log in/out button text in Polaris should be uppercase

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#370]
Currently SE version is uppercase but Polaris is not. Polaris should be updated to match.

**Comment by mxsnyder** [comment]
Done - https://ils-test.bcpl.lib.md.us/polaris/

**Comment by mxsnyder** [comment]
PR submitted

**Comment by mxsnyder** [comment]
@danfox01 https://ils-test.bcpl.lib.md.us/polaris/

Moving to r4r.
