### ISSUE TITLE
Download to Calendar does not work on iOS device

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#371]
Reported by Jason while testing events dev. This issue currently exists in prod:

In BrowserStack and on my personal iPhone, when I selected the “Download to Calendar” link, Safari displayed the screen shown below. No matter which blue link or taskbar symbol I clicked, I never saw an option to select the Calendar app.
![image](https://user-images.githubusercontent.com/13049389/39066384-e3195c80-44a2-11e8-8d5e-bdf6ac4f5c88.jpg)

**Comment by mxsnyder** [comment]
It turns out this is a known issue with iPhones. There are workarounds, but that's not a reasonable solution.

What if instead of downloading the ICS file, we email it to you?

**Comment by mxsnyder** [comment]
(emailed ICS files are supposed to work just dandy)

**Comment by danfox01** [comment]
@mxsnyder can you please send me a link to more detail on this issue? Forum post or something? Just want to understand the nature of it.

**Comment by mxsnyder** [comment]
I found an old article that suggests it's a mime-type issue:
https://apple.stackexchange.com/a/83523

I'll check it out.

**Comment by mxsnyder** [comment]
Requested the IIS mime types from Shep.

**Comment by mxsnyder** [comment]
For the fun of it, I uploaded an .ics file to SE and downloaded it on an iOS device via BrowserStack, and it worked great. So, this leads me to believe the problem is the ICS plugin.

**Comment by mxsnyder** [comment]
As an alternative, I could try implementing the iCal.net package in the BCPL web service, and serve iCal files that way. I don't know that it'll work any better, but it's worth a shot.

**Comment by danfox01** [comment]
As long as it won't take too long, let's try it.

**Comment by danfox01** [comment]
Verified in Browserstack. Nice work!

**Comment by mxsnyder** [comment]
File list:
- dist/js/apps/events-page/app.js
- dist/js/apps/events-page/partials/eventDetails.html
- dist/js/apps/events-page/partials/eventRegistration.html
- BCPL Web Service

**Comment by mxsnyder** [comment]
Created #400 for the bug fix.
