### ISSUE TITLE
Enable multi-item scrolling on book cover carousels

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#372]
**Current behavior:**
Clicking an arrow on the book carousel advances one item at a time.

**New behavior:**
Clicking an arrow advances the same number of items as currently show. For example, if 4 items are shown, clicking an arrow will advance to the next 4; if 3 items are shown, the arrow will advance to the next 3. And so forth, and so on, and what not, and what have you.

**Comment by mxsnyder** [comment]
This is a feature of slick. We just need to add the `slidesToScroll` setting. See the second example here:

http://kenwheeler.github.io/slick/

**Comment by mxsnyder** [comment]
'kay. 

https://dev.bcpl.info/

**Comment by danfox01** [comment]
This might be trickier than expected. It scrolls great at full width, but continues to scroll by 4 at smaller sizes.

**Comment by mxsnyder** [comment]
Fixed. I forgot to do the responsive settings.

**Comment by mxsnyder** [comment]
PR submitted

**Comment by danfox01** [comment]
Beautiful.
