### ISSUE TITLE
On 320px screens (iPhone SE) in Polaris, hamburger and search buttons don't scale properly.

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#375]
This issue only seems to affect screens at 320px. To replicate, compare SE global header to Polaris global header in Chrome's iPhone5 view. Note that the icons scale in the SE version, but stack in Polaris version. Polaris should be updated to match SE.

SE:
![fireshot capture 075 - baltimore county public library home_ - https___www bcpl info_](https://user-images.githubusercontent.com/13049389/39069517-ffe21b6c-44ad-11e8-83a1-47dfcc050c41.png)

Polaris:
![fireshot capture 076 - baltimore county _ - https___catalog bcpl lib md us_polaris_search_title aspx](https://user-images.githubusercontent.com/13049389/39069519-011203e4-44ae-11e8-9157-e97423b05893.png)

**Comment by mxsnyder** [comment]
![image](https://user-images.githubusercontent.com/24256320/39070728-7f4b9208-44b2-11e8-9bdd-8edfb414663f.png)

Done in dev. Submitting PR.

**Comment by danfox01** [comment]
Two things:
- the logo/buttons are slightly lower in Polaris than SE
- the icons are a bit larger in Polaris test than SE prod. I actually prefer the ones in Polaris test.

So...
- Can Polaris test be updated to match the logo/button spacing of SE?
- Can SE be updated to match the icon size of Polaris test?

**Comment by martypowell** [comment]
@danfox01 both requested changes are in their respective environments.

**Comment by danfox01** [comment]
Looks good.
