### ISSUE TITLE
Move Events filters below H1 at mobile size.

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#376]
On the [Events ](https://www.bcpl.info/events-and-programs/list.html#!/)page at mobile size, the filter component falls above the H1, but similar components on [Databases](https://www.bcpl.info/books-and-more/databases.html) and [Locations](https://www.bcpl.info/locations/index.html) appear below the H1.

Can the Events page be tweaked so that the the filters appear below the H1?

**Comment by martypowell** [comment]
@danfox01 the layouts for these two pages are different. Realistically we should probably consolidate the layouts so they are the same. This might be a good opportunity to start a blueprint for our atomic design and create one (see [here](http://bradfrost.com/blog/post/atomic-web-design/#templates))

**Comment by danfox01** [comment]
@martypowell, what's involved and how long would it take?

**Comment by martypowell** [comment]
@danfox01 per our discussion the creation of the documentation might be a half an hour. The template updates might be a day or two worth of work, with that including some heavy testing.
