### ISSUE TITLE
Update H1 style for blog posts

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#377]
When the templates changed in #368 it reminded me of a quick dynamic style fix I put in place for BCPL testing and forgot about.

The following is applied to the dynamic head section for blog posts, since some titles are too long and illegible in QuoteScript. Can we please get this into master so I can remove from dynamic style?

.blog-post h1 {font-family:Open Sans; font-size:2.2em; font-weight:700;}

**Comment by mxsnyder** [comment]
Done:
https://dev.bcpl.info/blog/2018/meet-the-book-club-the-page-turners

Submitting PR now.

**Comment by danfox01** [comment]
Approved.

**Comment by danfox01** [comment]
Resolved with Release 1.3
