### ISSUE TITLE
Margin issue with global nav panels on desktop

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#379]
Something is up with the horizontal spacing of the global nav elements on desktop. Specifically, check out Services, and note that the last item, "Licenses, Permits and Taxes" breaks onto two lines even though there's definitely space for it to fit on one.

I'm seeing a margin-right of 7em within the panels that is probably causing this.

**Comment by martypowell** [comment]
@danfox01 you said this was actually fixed now right?

**Comment by danfox01** [comment]
Yes, this was resolved when #384 was addressed.
