### ISSUE TITLE
AddThis modal in full detail view needs styling

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#392]
To replicate:
- Go to https://catalog.bcpl.lib.md.us/polaris/search/title.aspx?ctx=1.1033.0.0.6&cn=891923
- On the left, click "Share"
- Scream

I figure this should have the same black background  that AddThis usually has and should be centered.

**Comment by mxsnyder** [comment]
This is awful in more ways then my grasp of the English language can express.

**Comment by mxsnyder** [comment]
@danfox01 I took a look, and this is an `<iframe>` and due to same-origin policy, I can't inject CSS into it. I'm looking to see if others have hit this problem, but in the meantime, maybe we should consider removing Polaris's left-side share button.

**Comment by mxsnyder** [comment]
@danfox01 Nevermind, I was looking in the wrong place. I got it. Preview coming to a test website near you soon.

**Comment by mxsnyder** [comment]
@danfox01 Ready for preview:

https://ils-test.bcpl.lib.md.us/polaris/view.aspx?keyword=harry%20potter

**Comment by danfox01** [comment]
@mxsnyder Looks great on desktop, but weird on mobile. Let me know if you need "weird" defined, but I think you'll see it.

**Comment by danfox01** [comment]
Implemented in 1.4
