### ISSUE TITLE
Branch Name seems clickable but isn't on the Locations Page

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#394]
fyi - @danfox01 

i keep doing this

![image](https://user-images.githubusercontent.com/1933400/39280511-cdd9a756-48cd-11e8-94fd-25d113aa4991.png)

**Comment by danfox01** [comment]
Discussed with @sdurphy and @hburnopp. Let's change the second instance of the branch name to a static  header, "Address." That should solve the confusion about whether it's clickable, and makes things less redundant.

**Comment by martypowell** [comment]
Just to make this clear for me, Each branch name will change to "Address" which will be updated in the events app template.

**Comment by danfox01** [comment]
On the locations template, not events

**Comment by martypowell** [comment]
even better haha

**Comment by martypowell** [comment]
addressed by #470

**Comment by danfox01** [comment]
Resolved in 1.5.2
