### ISSUE TITLE
What is the process for updating only the nav in Polaris? Is it documented?

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#407]
@mxsnyder We are going to start having link and nav changes in the global header on a fairly regular basis. What is the best way to document what's changing to ensure the right stuff gets copied over?

Also, should small changes wait for a change control, or can they be updated on demand (assuming NSU is available, of course). I'd prefer for the nav not to be out of sync for very long.

**Comment by martypowell** [comment]
@danfox01 I will figure this out and get back to you

**Comment by danfox01** [comment]
Thanks. I thought Mike documented this somewhere but I can't find it.

**Comment by martypowell** [comment]
@danfox01 I think this is basically copy what is in dev or staging on a rendered page and move it into site.master in the polaris project. Next time we do this I can wrap the stuff that needs replaced in comments  (tracked [here](https://github.com/baltimorecounty/BCPL-assets/issues/423)).

**Comment by martypowell** [comment]
this is just waiting for the next update to the nav.

**Comment by danfox01** [comment]
@martypowell, to document our previous discussion:

SE has been updated with the global nav change. Just need to finalize the steps for getting it into Polaris. Not urgent but should be done sometime next week.

**Comment by martypowell** [comment]
@jsmith176 since you updated the nav, can you take a quick stab at this, basically just say exactly what you did.

**Comment by jsmith176** [comment]
@martypowell How detailed does this need to be? Are we talking programmer exact or something less technical?

**Comment by jsmith176** [comment]
The non-technical version:

- Navigate to the BCPL Home Page
- Inspect the changes (with chrome developer tools) noted in the issue
- Copy the changed elements into site.master
- Upload the changes

**Comment by martypowell** [comment]
@danfox01 see above. Is this sufficent?

**Comment by danfox01** [comment]
If we assume that @martypowell and @jsmith176 aren’t here (god help us), would this be enough info for another developer to figure out everything that needs to be done? If so, I’m good. If not, please add whatever additional info is needed. We should keep this somewhere easily accessible... maybe in the BCPL Github wiki?

Thanks!

**Comment by martypowell** [comment]
Yea I think this is probably sufficient then, but we might want to update our documentation on maintaining the Polaris skin to supplement this.

**Comment by martypowell** [comment]
These are located in the readme, for the tfs project.

**Comment by martypowell** [comment]
@danfox01, @jsmith176 reviewed these and is comfortable with the changes.
