### ISSUE TITLE
AddThis not functioning properly on Events page

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#409]
BCPL reported that nothing happens when they select the "Share" button on the events page. I have not been able to replicate this in any browser **but** I did discover another issue:

When clicking the Share button on an event detail screen, the link defaults to the main Events page (https://www.bcpl.info/events-and-programs/list.html#!) instead of the specific event (e.g, https://www.bcpl.info/events-and-programs/list.html#!/141761)

I think this might be what we need to do? https://www.addthis.com/academy/install-addthis-angularjs/

**Comment by danfox01** [comment]
Also, I realize some of the functionality is redundant to the "Email to a Friend" feature on the left, but for the sake of template consistency the share button should work on every page

**Comment by martypowell** [comment]
@danfox01 oh how i love addthis, going to attempt to do this one.

**Comment by martypowell** [comment]
@danfox01 this is in dev.

**Comment by danfox01** [comment]
Looks good.

**Comment by danfox01** [comment]
Resolved in v1.5.2
