### ISSUE TITLE
Document BCPL Services

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#410]
http://services.bcpl.info/

Probably best to use swagger at this point.

**Comment by martypowell** [comment]
@danfox01 - This was overwritten on testservices, so that we could test the download endpoint, the docs and the download changes will be merged prior to the next release

**Comment by martypowell** [comment]
@danfox01 these are done, we will need to make sure these are maintained on each change.

**Comment by danfox01** [comment]
Awesome. What is the link for BCPL?

**Comment by martypowell** [comment]
dan, this is missing a couple things, updating this now.
