### ISSUE TITLE
Polaris "My Account" menu disappears on small screens

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#412]
When browsing account features (https://ils-test.bcpl.lib.md.us/polaris/patronaccount/), the "My Account" menu disappears at small sizes.

To replicate:

- View the site at 650 px, scroll down and note that "My Account" shows.
- Size down to 649 px or smaller, and note that "My Account" disappears.

"My Account" menu should show at all sizes.

**Comment by martypowell** [comment]
@danfox01 ready for review in dev.

**Comment by danfox01** [comment]
Implemented in 1.4
