### ISSUE TITLE
Add to List is showing as a link instead of a button

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#418]
The Add to List button (underneath Place Hold on the left side) is rendering as a link, but turning back into a button on hover. I am seeing this in all cases in Chrome on my PC. @sdurphy says it's displaying normally on his Mac.

https://catalog.bcpl.lib.md.us/polaris/search/title.aspx?ctx=1.1033.0.0.6&cn=13374

**Comment by martypowell** [comment]
@danfox01  in all major window browsers on the county network, this looks okay to me.

**Comment by danfox01** [comment]
Implemented in 1.4.1
