### ISSUE TITLE
Add interaction tracking to GA

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#448]
Specifically, I would like to know when major UI elements are interacted with -- for example, button clicks, filter changes, etc.

**Comment by martypowell** [comment]
We want to be able to track events for anything. Take a look at https://github.com/baltimorecounty/BCPL-assets/blob/integration/js/utility/bc-google-analytics.js.

We want to add  a function to this file called "trackEvent". That function should accept:
- category (required)
- label
- value (required)

see [here](https://developers.google.com/analytics/devguides/collection/gtagjs/events)

@danfox01 fyi

**Comment by jsmith176** [comment]
@marty we should probably require an action as well

**Comment by martypowell** [comment]
@jsmith176 you are right, I updated my comment above.

**Comment by martypowell** [comment]
@danfox01is there a certain interaction that you want to start tracking?

**Comment by danfox01** [comment]
Re: your questions from a few days ago (sorry, didn't see it till now) -- yes, I think Swiftype covers everything we need for search.

I am most curious about tracking filter usage -- events, locations, databases.

**Comment by martypowell** [comment]
sounds good, ill add an issue or two so we can do this.

**Comment by danfox01** [comment]
Resolved with 1.5.4
