### ISSUE TITLE
High Contrast does not persist when navigating to a new page

### ISSUE THREAD

**Issue by jsmith176** [baltimorecounty/BCPL-assets#455]
1. Set the Adjust Contrast toggle to true.
2. Navigate to a new page.

The toggle button is now false and the high contrast style is lost.

4. Set the Adjust Contrast toggle to true.
5. Click the back button.

The toggle is in the true position, isHighContrast is false, and the high contrast style is lost.

**Comment by danfox01** [comment]
@jsmith176 very good catch. @martypowell can we look into a HF for this after today's release is out the door? The contraster is actually a really big deal for accessibility,.

**Comment by martypowell** [comment]
@danfox01 yes

**Comment by martypowell** [comment]
@danfox01 assigned to josh, he is going to start workign on it

**Comment by martypowell** [comment]
this was pushed on 5/17
