### ISSUE TITLE
Events - Adjust card layout at md screen size

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#458]
![image](https://user-images.githubusercontent.com/1933400/40125382-c8ca6a9e-58f8-11e8-98e9-5ed7c72780c1.png)

**Comment by martypowell** [comment]
This sized screen should also look like, with the time and branch above the other information.

![image](https://user-images.githubusercontent.com/1933400/40125493-11e5f694-58f9-11e8-9a9e-0f7f9587c989.png)

@danfox01 moved to a priority

**Comment by danfox01** [comment]
@martypowell, renames this issue to make it better match the solution we discussed.

**Comment by danfox01** [comment]
Thanks @jsmith176! This looks good in dev. I am reopening until this goes into production. That's generally how we want to do it, so we don't lose track of the changes between releases.

**Comment by jsmith176** [comment]
@danfox01 I will keep that in mind for the next one!

**Comment by danfox01** [comment]
One change: At full size, the event card cols should be 4 and 8, not 3 and 9.

You can compare that breakpoint to prod to see the expected widths. They are correct in prod.

**Comment by jsmith176** [comment]
@danfox01 this is ready for testing again. The changes are in dev.

**Comment by danfox01** [comment]
Looks good. Thanks!

**Comment by danfox01** [comment]
Resolved in 1.5.2
