### ISSUE TITLE
Polaris is accessible over http

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#462]
Account features seem to require https, but shouldn't we be forcing https everywhere?

**Comment by martypowell** [comment]
@danfox01 sheppard is going to look into this for us.

**Comment by mjsheppard74** [comment]
DONE. you guys can check this one off. Test it out and let me know if you see any issues.

**Comment by danfox01** [comment]
Looks good to me. Thanks @mjsheppard74. @jdomasky can you please take a quick look as well, before I close it out?

**Comment by jdomasky** [comment]
The problem appears to be fixed. IE was previously able to hold onto an http connection (for the main page only) after the cache was cleared. Today, it's consistently refreshing to https.

**Comment by martypowell** [comment]
awesome thanks @mjsheppard74 and welcome 😄
