### ISSUE TITLE
Alternative designs for "Registration" and "Children Under 8" on Events page

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#466]
We have discussed this a little bit but made no decisions. The addition of the age disclaimer for most events has made the events page feel pretty red-heavy. Any ideas?

https://www.bcpl.info/events-and-programs/list.html#!/

**Comment by danfox01** [comment]
That's a possibility. I was thinking maybe a key at the top and then just icons on the cards or something. Or maintain the disclaimer on the cards but try to tone down the intensity.

**Comment by jsmith176** [comment]
Maybe change them to the purple color of the event date bar?

**Comment by jsmith176** [comment]
![image](https://user-images.githubusercontent.com/2495453/40254176-7973d192-5ab0-11e8-8156-85f4a664704f.png)

**Comment by jdomasky** [comment]
I like your suggestion a lot, @jsmith176! It no longer feels red-heavy to me.
I'm concerned about putting the disclaimers at the top and using icons because I've never regarded key/icon systems to be mobile-friendly.

**Comment by danfox01** [comment]
You're on the right track @jsmith176 -- purple definitely softens everything and I like that it keeps with the brand colors.  I think we would still be in the same position, though -- only too much purple now, instead of too much red.

I think it's might actually be more of a text problem than a color problem. It's just a lot with the addition of the second tag. @sdurphy any thoughts?

**Comment by jsmith176** [comment]
@danfox01 How do you feel about this color? (#a12600)
![image](https://user-images.githubusercontent.com/2495453/40316497-844ff17a-5cec-11e8-8805-1411f28b07b9.png)
It's the complementary color of the header.

**Comment by sdurphy** [comment]
Can we simplify so that the star is purple (#802754) and the text is dark gray (#666). Please see attached mockup.
![screen shot 2018-05-22 at 9 42 39 am](https://user-images.githubusercontent.com/2189638/40366352-e572ba4c-5da4-11e8-9982-2c97453031aa.png)

**Comment by ascire** [comment]
`#666` is the Gray of the Beast.

\*Exits thread.\*

**Comment by jsmith176** [comment]
It looks good though.

**Comment by sdurphy** [comment]
HAHAHA @ascire

**Comment by danfox01** [comment]
Let's go with @sdurphy's version. Moving this to To-Do.

**Comment by martypowell** [comment]
@danfox01 this is in dev, please verify that @jsmith176 's changes are still reflected with the responsiveness.

**Comment by danfox01** [comment]
Confirmed, looks good.

**Comment by danfox01** [comment]
@martypowell this is still marked pending code review. Good to close?

**Comment by danfox01** [comment]
Resolved in 1.5.2
