### ISSUE TITLE
Update Polaris global nav to match BCPL SE nav

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#471]
See also: #423 and #407. This change is minor, but we need to make sure the process is documented as well.

The specific changes that need to be translated to Polaris in this update:

- Additional "Summer Reading Challenge" `<li>` added to Youth section
- "Log in to Your Account" `<h3>` in slide down-nav is now "Your Account"

**Comment by martypowell** [comment]
@jsmith176 FYI

**Comment by jsmith176** [comment]
@danfox01 This is ready for testing.

**Comment by danfox01** [comment]
Something is still funky here. If you open two tabs and toggle back and forth between Polaris and SE you can see some differences at identical sizes. Also, when you size down 320 (iPhone SE size), menu icons stack instead of shrinking in Polaris.

**Comment by martypowell** [comment]
@danfox01 i did not mean to assign to you.

**Comment by jsmith176** [comment]
@danfox01 This is ready for testing. It also addresses the "Digital Materials" heading in the slide-out global nav no longer being styled properly. It should be the correct font now.

**Comment by danfox01** [comment]
@jsmith176 can you please double check? I'm not seeing these in test. http://ils-test.bcpl.lib.md.us/polaris/

**Comment by jsmith176** [comment]
@danfox01 Woopse! Should be there now.

**Comment by danfox01** [comment]
Looks like the Summer Reading Challenge nav link got dropped from Polaris at some point. Can we get those back in?

There should be an <li> for "Summer Reading Challenge" in the **Events and Programs** menu and the **Youth** menu. Please see the BCPL site in SE for exact placement: www.bcpl.info. They should match.

**Comment by martypowell** [comment]
@danfox01 summer reading has been added to production.

**Comment by danfox01** [comment]
Confirmed in prod.
