### ISSUE TITLE
Polaris menu icons are smaller than SE versions

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#472]
Polaris search and hamburger icons are smaller than SE versions at XS screen size. The Polaris header should be updated to match the sizes and breakpoints of SE.

SE on left, Polaris on right. I believe this was introduced by #387.

![screenshot-2018-5-21 baltimore county public library home](https://user-images.githubusercontent.com/13049389/40327205-152829ba-5d10-11e8-922b-5217c6743c8a.jpg)

**Comment by danfox01** [comment]
Per conversation with @martypowell.

At XS size, the buttons should look like the screenshot on the left, until you hit 320px, which is the smallest size we currently support (iPhoneSE). At 320, the buttons should shrink to fit and look more like the nav on the right. The issue is that in Polaris currently, the buttons shrink sooner than they should.

Super short version: The way that it looks in prod SE is correct. Polaris should be updated to match that exactly.

**Comment by jsmith176** [comment]
@danfox01 This is ready for another look.

**Comment by danfox01** [comment]
@jsmith176, This is really close. Two things:

- The "Digital Materials" heading in the slide-out global nav is no longer styled properly in ils-test... it should be TT Rounds Bold like the other top-level items.
- It looks like the button heights are a little different in SE vs. Polaris. This is not a showstopper, but if it's easily fixable, Polaris should match SE. I doubt many people will notice, but if you flip back and forth, you can tell.

**Comment by jsmith176** [comment]
@danfox01 the button sizes look correct now. They may have been fixed as a side effect of updating the Polaris global nav.

**Comment by danfox01** [comment]
@jsmith176, indeed they do. Let's consider this as ready to release when Polaris test gets pushed to prod. Last I heard that will happen on June 24.

**Comment by danfox01** [comment]
Confirmed in prod.
