### ISSUE TITLE
When contraster is active, breadcrumb arrows get huge in IE11

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#474]
Reported by @jdomasky. Not the results of a recent change -- this currently exists in prod as well.

To replicate, turn contraster on in IE11 and note the hugeness of the breadcrumb.

**Comment by martypowell** [comment]
@danfox01 this fix is in dev.

**Comment by danfox01** [comment]
Confirmed in dev.

**Comment by danfox01** [comment]
Released in 1.5.2
