### ISSUE TITLE
Add a Class for Captioned Images

### ISSUE THREAD

**Issue by sdurphy** [baltimorecounty/BCPL-assets#480]
We need a class for images with captions. Basically a user should be able to create a div, insert an image into that div and place a caption below the image that conforms to the width of the image. The image and caption should be responsive. Comps are attached.  
![caption-desktop](https://user-images.githubusercontent.com/2189638/40446173-5c665e36-5e9c-11e8-9302-744bddf1d42c.png)
![caption-mobile](https://user-images.githubusercontent.com/2189638/40446174-5c74d5ce-5e9c-11e8-9383-2e96e386efd7.png)

**Comment by martypowell** [comment]
pr #505 fixes this issue.

**Comment by danfox01** [comment]
Resolved with 1.5.4
