### ISSUE TITLE
Image widths should be defined by CSS

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#481]
Currently images are being scaled by SE and stuff is getting weird. I think we want our CSS classes to handle the scaling instead.

Sort of guessing here, but 40% seems like a good target for images that have text wrap, though Sam might want other options. At XS size, I think 100% width would work for everything.

Needs a little more discussion with @martypowell and @sdurphy. Open to suggestions of course.

**Comment by martypowell** [comment]
@danfox01 can you please confirm this is what we are looking for?

**Comment by danfox01** [comment]
I'm seeing one issue that may just need a process change regarding image size when we upload.

At desktop, sometime images smaller than 250px are used. When you size down to mobile, these seem to scale up, which makes them pixelated. This would be especially noticeable on a mobile device with hi res display.

For example, see this post and reduce to mobile size: https://dev.bcpl.info/blog/2018/between-the-covers-with-helen-hoang

**Comment by martypowell** [comment]
this has been resolved with #506

**Comment by danfox01** [comment]
Resolved with 1.5.4
