### ISSUE TITLE
Polaris - Reading History needs tablenated

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#488]
https://ils-test.bcpl.lib.md.us/polaris/patronaccount/readinghistory.aspx?ctx=1.1033.0.0.6

**Comment by jsmith176** [comment]
@danfox01 the reading history in ils-test has some different columns than in production.

**Comment by jsmith176** [comment]
@danfox01 This is in ils-test and is ready for testing.

**Comment by danfox01** [comment]
@jdomasky, do you have reading history turned on in prod? I can't verify if this table was tablenated in prod because I don't have a history,.

**Comment by danfox01** [comment]
Thanks!
