### ISSUE TITLE
Thumbnails and article titles in blog list and landing views don't need link titles

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#489]
The structured content layout appears to by dynamically generating link titles for these two elements by pulling in the post titles and using it as link title. This technically isn't needed because we don't enforce link titles anymore. Ideally, these fields would not be included. Low priority.

**Comment by martypowell** [comment]
@danfox01 please test in dev.

https://dev.bcpl.info/blog

**Comment by danfox01** [comment]
I'm seeing one issue that may just need a process change regarding image size when we upload.

At desktop, sometime images smaller than 250px are used. When you size down to mobile, these seem to scale up, which makes them pixelated. This would be especially noticeable on a mobile device with hi res display.

For example, see this post and reduce to mobile size: https://dev.bcpl.info/blog/2018/between-the-covers-with-helen-hoang

**Comment by danfox01** [comment]
Looks good.

**Comment by martypowell** [comment]
resolved by #505 and similar to #480

**Comment by martypowell** [comment]
@danfox01 in production.
