### ISSUE TITLE
Polaris - Contraster not working

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#490]

**Comment by jsmith176** [comment]
@danfox01 this is in ils-test and is ready for testing.

**Comment by danfox01** [comment]
Looks good!

**Comment by jsmith176** [comment]
This will be temporarily broken in ils-test since it gets the js files from prod.
The contraster should work again after the next release.

**Comment by danfox01** [comment]
Confirmed in prod.
