### ISSUE TITLE
For Keyword Search Results page, move "Search By" and "Limit By" dropdowns into same box as "Keyword search"

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#492]
On mobile, this would also mean that the "Select Options" button goes away, and these three fields are always shown.

https://ils-test.bcpl.lib.md.us/polaris/search/searchresults.aspx?ctx=1.1033.0.0.6&type=Default&term=harry%20potter

**Comment by martypowell** [comment]
@danfox01 should select options work the way it does now on larger screens?
