### ISSUE TITLE
Height of drop-down menus should match heigh of text inputs on Advanced Search

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#493]
https://ils-test.bcpl.lib.md.us/polaris/search/default.aspx?ctx=1.1033.0.0.5&type=Advanced

Can the drop down menus on this page be aligned to match the height of the text inputs next to them?

**Comment by martypowell** [comment]
@danfox01 

![image](https://user-images.githubusercontent.com/1933400/40800334-1ab6f0b6-64de-11e8-938e-6166317bc2bf.png)

???

**Comment by martypowell** [comment]
@danfox01 this is in test, please let me know what you think?

**Comment by danfox01** [comment]
Looks good to me!

**Comment by danfox01** [comment]
@martypowell, let me know if I should move this to ready to release.

**Comment by martypowell** [comment]
@danfox01 it is ready, so I moved for you.

**Comment by danfox01** [comment]
Confirmed in prod.
