### ISSUE TITLE
"More Search Options" modal isn't working in test

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#494]
When you select "more search options" after running a keyword search, the modal appears but doesn't work correctly.

- The button in the lower right reads "undefined." In prod, the buttons are "Set Search Options" "Clear" and "Close."

- Changes don't actually update the search query.

- The Exclude checkboxes in the modal don't align properly in test.

Compare to prod for proper functionality.

**Comment by martypowell** [comment]
@danfox01 please verify the modal in test, I don't think any of the changes were necessary.

**Comment by danfox01** [comment]
Marty, documenting what we discussed in Hangouts. I don't think we need the additional styling -- the way it looks now is fine. Jason retested and it sounds like he's still  have sporadic issues with the "undefined" button appearing. I wonder if it's because of the lag in test.

**Comment by martypowell** [comment]
@danfox01 it's the lag in test, doesn't seem like there is anything we can do about that. I think this can be resolved.

**Comment by danfox01** [comment]
Yup, agreed. Thanks Marty.
