### ISSUE TITLE
Add Event Tracking to Event Filters

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#495]
Events to track

- Keyword Search
  - action: "Keyword Search"
  - category: "Events"
  - label: the actual search term
- Start/End Date Change
  - action: "{Start/End} Date Filter Selection"
  - category: "Events"
  - label: the new date 
- Filter List Checkbox Click 
  - action: "{groupHeading} Filter Selection" (ex: "Branches Filter Selection")
  - category: "Events"
  - label: the actual selection + whether it's checked or not (ex: "Arbutus - Selected", ""Arbutus - Unselected")

**Comment by danfox01** [comment]
This looks good to me.

**Comment by martypowell** [comment]
@danfox01 you can test this in dev. You will see the output in the console so that we can "debug" this logic. When debug mode is turned off, it will send it to google analytics.

![image](https://user-images.githubusercontent.com/1933400/40916778-04ac7464-67cf-11e8-93fb-28a7214dd291.png)

**Comment by danfox01** [comment]
Sweet. Looks good.

**Comment by danfox01** [comment]
Resolved with 1.5.4
