### ISSUE TITLE
Featured Events Widget is only Displaying 3 Events when it's set to 4

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#501]
@danfox01 fyi.

**Comment by martypowell** [comment]
This appears to be happening because the events being returned are in a smaller date range than we desire.

**Comment by martypowell** [comment]
@danfox01 this is in dev, hotfix is pending pull request.

**Comment by danfox01** [comment]
Looks good to me in dev. Thanks Marty.

**Comment by martypowell** [comment]
will be released as a hotfix as soon as the code has made it through pr.

**Comment by martypowell** [comment]
Released as hotfix [1.5.3](https://github.com/baltimorecounty/BCPL-assets/releases/tag/1.5.3)
