### ISSUE TITLE
Adding Pagination and Filtering to Blog

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#509]
fyi @danfox01 

@sdurphy is reaching out to Systems to see if this is possible.

**Comment by danfox01** [comment]
Sorry, I put in a ticket for this a few months ago when Mike was still here. They said something to the effect if, it's possible if we want to write our own custom container:

> Hi Dan,
> 
> I've reached out to our senior web dev, and can state that the built-in pagination is available only on the list layout. A way to include paging on a landing page would be to use a custom container where you would write your own pagination functions. Hope this helps.
> 
> Thanks,
> 
> Emad Ahmed, Support Engineer
>

**Comment by martypowell** [comment]
To clarify on this the requirements for this specific problem are to be able to filter by category and have a numbered list of pages.

**Comment by martypowell** [comment]
@jsmith176 please add a parameter for and/or to the GetFilterQuery method in the ExpressionHelper

**Comment by danfox01** [comment]
@martypowell, what is the status of this, and the filtering enhancement?

**Comment by martypowell** [comment]
in progress, currently the api is in a pull request, once that is approved, we can start moving the app to dev.

**Comment by danfox01** [comment]
This was addressed by https://github.com/baltimorecounty/react-blog/releases/tag/1.0.0
