### ISSUE TITLE
Research - Allow "Remember Me" option when logging in

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#510]
fyi @danfox01 

This is a top BCPL wish list item. Please research the feasibility and security of this. Not sure what’s involved, or if this is even possible

**Comment by martypowell** [comment]
@danfox01 just to clarify, I'm assuming they want both username and password remembered?

**Comment by martypowell** [comment]
I think this is probably something we would need to request from the vendor as the only implementations I can find as best practice need to happen on the server side.

**Comment by danfox01** [comment]
Thanks @martypowell. I referred this to Cathy as a potential vendor enhancement and she raised a number of concerns regarding security policy that would need to be addressed at the management level, before we even pursue the question further. Closing, since this will likely never see light of day.
