### ISSUE TITLE
Implement Google CustomSearch API

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#518]
Implement the research done here, https://github.com/baltimorecounty/BCPL-assets/issues/498

**Comment by martypowell** [comment]
👍

**Comment by danfox01** [comment]
This has been approved and purchased. Hit me up for API keys and other info when you're ready to get started.

We will need to implement this on BCG and BCPL sites. Ideally I'd like to have it in place in prod by Sept. 14, since our Swiftype contract ends at the end of the month.

**Comment by martypowell** [comment]
to update this threads, we are going with Google Custom Search to start

**Comment by danfox01** [comment]
This was implemented in release 1.6. Also, changing issue name to reflect the actual solution that was implemented.
