### ISSUE TITLE
Some modals are not opening in ILS-Test

### ISSUE THREAD

**Issue by jsmith176** [baltimorecounty/BCPL-assets#519]
Steps to reproduce (first modal):
1. Perform a keyword search.
2. Click on the format icon (i.e., book symbol) below the cover art.
 
Steps to reproduce (second modal):
1. Log into account.
2. View Items Out.
3. Click on the info sign glyph (i.e., “i” in a circle) in right column.
 
Steps to reproduce (third modal):
1. Log into account.
2. View your Fees.
3. Click on Estimate Overdue Fines.
 
Notes:
In IE and Firefox, when you browse a list of titles in ILS-Test search results, the format icon that appears below the cover art is clickable.
When I click the format icon, the mouse cursor changes to a hand, but nothing happens.
In comparison, in Polaris prod, when I click the format icon, a modal window opens to display the item details.
 
Also, in My Account, on the Items Out page, each item in the list has an info sign glyph in the right-most column, which is clickable.
In ILS-Test, when I click the glyph, the mouse cursor changes to a hand, but nothing happens.
In comparison, in Polaris prod, when I click the glyphs on the Items Out page, a modal window opens to display the item details.
 
And finally, in My Account > Fees, the Estimate Overdue Fines button functioned properly on June 1, when I last performed the Polaris test.
This week, the button seems to do nothing when it’s clicked.

**Comment by martypowell** [comment]
@jdomasky ready for another look.

**Comment by jdomasky** [comment]
All three modals are now opening, as expected, after testing in multiple browsers at the major breakpoints. This issue is resolved.
