### ISSUE TITLE
 About RSS Page Is Missing White Content Container, But Container Is Present in Production

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#520]
When I compare https://ils-test.bcpl.lib.md.us/polaris/rss/whatis.aspx with prod, the content isn’t displayed with a white background, like it is in prod:
https://catalog.bcpl.lib.md.us/polaris/rss/whatis.aspx

**Comment by martypowell** [comment]
@jdomasky ready for another look.

**Comment by jdomasky** [comment]
@martypowell this is resolved. The RSS page in ILS-Test is now identical to production.
