### ISSUE TITLE
Self-Registration Form in ILS-Test Has No H1 and an Extra Field Not in Production

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#521]
In ILS-Test, the self-register form has a “Language Preference” field that doesn't display in prod.
This field includes instructions that overlap the dropdown.
The form page has no H1 and the form has other layout issues.
In prod, an H1 (“Register”) is displayed.
 
Steps to reproduce:
1. Link: https://ils-test.bcpl.lib.md.us/polaris/patronaccount/selfregister.aspx?ctx=1.1033.0.0.6
1. Select a branch and submit a ZIP code.
1. Issues can be viewed on the next page, which is the full registration form.

**Comment by jsmith176** [comment]
@danfox01 this is in ils-test and is ready for testing.

**Comment by danfox01** [comment]
@jdomasky, can you take a look please?

**Comment by martypowell** [comment]
@jdomasky we needed to get this code ready for production, it looked good to both @danfox01 and I. I am making a note that there is potential risk which opens up the possibility for a hotfix.

**Comment by jdomasky** [comment]
The form looks good to me in IE! Thanks for moving forward on this.

**Comment by jdomasky** [comment]
Now that the upgrade is complete, I noticed that the "Language preference" field is missing on the self-registration form in prod. This field still exists in ILS-Test.
I'm unsure if this is intentional, but regardless of the reason, this issue was not a waste of time because the H1 was needed.
Compare: https://catalog.bcpl.lib.md.us/polaris/patronaccount/selfregister.aspx
...with: https://ils-test.bcpl.lib.md.us/polaris/patronaccount/selfregister.aspx

**Comment by martypowell** [comment]
My guess is this is some sort of configuration, @jdomasky can you please check with Karrie to see if this is true?

**Comment by jdomasky** [comment]
Good idea! I made an inquiry. I'll share her reply.

**Comment by jdomasky** [comment]
@martypowell @danfox01 End of week update: Email was sent on June 26. I'll follow-up next week if no response is received.

**Comment by jdomasky** [comment]
@martypowell @danfox01 Karrie met with me yesterday and we confirmed the difference between dev and prod. She is going to investigate.

**Comment by martypowell** [comment]
@jdomasky was there ever any update on this?

**Comment by jdomasky** [comment]
@martypowell ...no. I'm going to follow-up again.

**Comment by jdomasky** [comment]
Update: On August 14, I reminded Karrie. She replied the same day, stating that she was looking at the problem right away. No follow-up reply has been received.

**Comment by martypowell** [comment]
@jdomasky karrie followed up wiht me and we both agreed, this wasn't really a big issue.
