### ISSUE TITLE
Estimate Overdue Fines Button Appears in ILS-Test, But Is Missing in Production

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#522]
In ILS-Test, on the “My Account > Fees” and “My Account > Items Out” pages, below the Charges/Deposits/Credits table, an “Estimate Overdue Fines” button appears.
The button doesn’t work at this time, but it functioned correctly on June 1.
In prod, this button is not displayed on these pages.

**Comment by martypowell** [comment]
this appears to be related to #519, once that code is integrated this will be ready for test.

**Comment by martypowell** [comment]
@jdomasky ready for another look.

**Comment by jdomasky** [comment]
Although the button is not displayed in prod, this issue is resolved in dev. The button functions correctly by opening a modal.
