### ISSUE TITLE
Large Cover Image Is Not an Option in ILS-Test, But It Appears in Production

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#523]
In ILS-Test in Full Display mode, I don’t see a drawer for Large Cover Image.
This option is present in prod.

**Comment by martypowell** [comment]
it sounds like this might be a product of test...we will rollback to the vendors version to see if this is still an issue.

**Comment by jdomasky** [comment]
Steps to recreate this issue:

1. Browse dev: https://ils-test.bcpl.lib.md.us/polaris/search/title.aspx?ctx=1.1033.0.0.6&cn=7713
2. Scroll down to the drawers and observe that 'Large Cover Image' is missing.
3. Browse prod: https://catalog.bcpl.lib.md.us/polaris/search/title.aspx?cn=7713
4. Scroll down to the drawers and observe that 'Large Cover Image' is present.

**Comment by martypowell** [comment]
per karrie

"Most of those tabs come from Syndetics and, as far as I remember, that is not set up in Test."

closing.
