### ISSUE TITLE
Email Saved List Broken in ILS-Test, But Works OK in Production

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#524]
While viewing a saved list in ILS-Test, when I type an email address (jason.domasky@gmail.com or jason@bcpl.net) in the box at the top of the list, and click “Email Page to:” or “Email All to:,” the page reloads and displays the screenshot below, which is an error message.
This procedure works correctly in prod.

**Comment by martypowell** [comment]
@danfox01 @jdomasky i feel like this never worked in test, i dont have any concrete evidence. Do either of you have any ideas?

**Comment by jdomasky** [comment]
@martypowell @danfox01 this is the first time I've tried the Email Saved List feature in ILS-Test. It's possible it never worked. This feature isn't covered by the Polaris test plans.

**Comment by martypowell** [comment]
@jdomasky no problem, dan i talked about this and we will something we will address as a hotfix as needed

**Comment by martypowell** [comment]
per @danfox01 email works in production, IT DOES NOT in test. This is something we should document in our test plans.
