### ISSUE TITLE
Update Blog Tabs Mobile Menu

### ISSUE THREAD

**Issue by sdurphy** [baltimorecounty/BCPL-assets#526]
For the blog, at mobile size can the tabs mimic the behavior of the tabs on the book carousel at the bottom of the BCPL index? I've attached a comp.

![mobile](https://user-images.githubusercontent.com/2189638/41730307-82188bae-7549-11e8-8010-791ee9bccab3.jpg)

**Comment by martypowell** [comment]
@sdurphy we should also do this for the tabs on the homepage for new arrivals correct?

**Comment by danfox01** [comment]
Sorry guys, late to this party. I know I'm really behind. I thought we were going to be using the standard filtering UI we use on other pages (databases, locations, etc.). Is there a reason we don't want to do that?

**Comment by martypowell** [comment]
Dan you are talking about taking this (mocked up version)

![image](https://user-images.githubusercontent.com/1933400/41734391-be36c852-7554-11e8-8b77-e61ff110c964.png)


and making it look like...

![image](https://user-images.githubusercontent.com/1933400/41734402-cb4fcebc-7554-11e8-8093-4afa9cc3b17b.png)

**Comment by danfox01** [comment]
Yeah, I must have completely missed the mockup or I would have mentioned this sooner. BCPL wants to add additional tags over time, so the tabs could get unwieldy. If it's a filter list it's easier to add to.

**Comment by danfox01** [comment]
This is actually no longer relevant due to changes to the blog UI.
