### ISSUE TITLE
When viewing a full title record, the "Add to List" button shows as a link instead of styled as a button

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#530]
Jason sees this issue in IE11 and Chrome, Michael sees it in IE11 only, and I'm not seeing it at all. This is an issue we've had in the past -- can you look into it?

https://catalog.bcpl.lib.md.us/polaris/search/title.aspx?ctx=1.1033.0.0.6&cn=924682

**Comment by martypowell** [comment]
@danfox01 i went on browserstack and tested about 12 browsers, 6 on windows 10, 6 on ios and could not replicate this.

**Comment by martypowell** [comment]
per @danfox01 the testing was sufficient to close this.
