### ISSUE TITLE
At mobile size, global search button changes size when active

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#531]
Occurs in Polaris only, at mobile sizes.

![fireshot capture 093 - baltimore county public library_ - https___catalog bcpl lib md us_pol](https://user-images.githubusercontent.com/13049389/41828732-e5b5d636-7804-11e8-9dcd-c51613d26e5b.png)

**Comment by jsmith176** [comment]
@danfox01 this is ready for testing.

**Comment by danfox01** [comment]
Looks good.

**Comment by danfox01** [comment]
@jsmith176 @martypowell Can we release this today, please?

**Comment by martypowell** [comment]
@danfox01 yes, looking at this now.

**Comment by martypowell** [comment]
@danfox01 please confirm.

**Comment by danfox01** [comment]
Perfect, thanks.
