### ISSUE TITLE
esources.aspx not displaying propertly

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#532]
https://catalog.bcpl.lib.md.us/polaris/search/misc/esources.aspx?Category=80

This is the vendor's version. Seems like it's missing the navigation.

**Comment by martypowell** [comment]
related to #527, but it appears our style changes are okay

**Comment by martypowell** [comment]
@jsmith176 @danfox01 ... dan is going to have michael look into this to see if its an issue inside polaris

**Comment by danfox01** [comment]
Looks like Polaris truncated the descriptions in the new version which, cut off a bunch of closing tags in the markup, Michael removed the descriptions in the client, since they're no longer needed anyway. Resolved.
