### ISSUE TITLE
BCPL emergency alert banner does not seem to honor start time set in structured content

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#535]
We posted an alert banner that was scheduled to post at 9 a.m. It showed up immediately after being published, 15 minutes before the time we specified. It still came down at the correct scheduled time.

**Comment by martypowell** [comment]
as dicussed over chat @danfox01 will "alert" me when this situation is available in production again. @sdurphy level pun here.

**Comment by sdurphy** [comment]
![clapping-gif-2015](https://user-images.githubusercontent.com/2189638/41872679-a620c666-7890-11e8-8e6c-e6bba08a27e5.gif)

**Comment by martypowell** [comment]
@danfox01 any luck with this?

**Comment by danfox01** [comment]
Unable to replicate. Closing for now, will reopen if it occurs again.
