### ISSUE TITLE
"Check In" button for Polaris e-content doesn't work

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#536]
Confirm by Jason and Michael... the "Check In" button that appears on the Items Out page should do ... something. Currently selecting it doesn't check the item back in or provide any kind of feedback.

![image1](https://user-images.githubusercontent.com/13049389/41868726-de101f92-7884-11e8-95e6-691c07ee7cc1.jpg)

**Comment by martypowell** [comment]
@danfox01 this has been implemented in prod and confirmed by @jdomasky

**Comment by danfox01** [comment]
Thanks!
