### ISSUE TITLE
Ensure Mobile Menu is Easily Selectable on Smaller Screens

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#537]
Visit http://catalog.bcpl.lib.md.us/polaris/ on a smaller sized screen. 

![image](https://user-images.githubusercontent.com/1933400/41909213-7431bcbc-7914-11e8-9979-9e0ff577be87.png)

If you select anywhere inside of the red circles nothing will happen. If you compare that to bcpl.info, you the menu should should function as expected.

fyi @danfox01

**Comment by danfox01** [comment]
@tmccoy529 what is the status of this one?

**Comment by tmccoy529** [comment]
The issue was resolved but adding a width to the button so it would span the length of the row. The empty space should now be clickable.

**Comment by danfox01** [comment]
Yeah I thought I saw this working in ILS-TEST a few days ago but I'm not seeing it now. Can you please double check that it's still there? There are some other issues with menu font weights that seem to have popped in recently too. Not sure where they originated.

**Comment by tmccoy529** [comment]
I moved integration branch back over to test. Looks like its back. I have been working on another bug so I'm guessing I didn't get the latest from integration before I pushed my new branch over. Sorry about that.

**Comment by tmccoy529** [comment]
Dan, can you test this issue? Test should be restored back to the correct branch. Thanks!!

**Comment by danfox01** [comment]
Confirmed. Looks good. Thanks!

**Comment by martypowell** [comment]
I had to manually add this in production, it seems like somethign isn't right. Like maybe the scss didn't get updated. @jsmith176 @tmccoy529 we will need to investigate.

**Comment by tmccoy529** [comment]
@martypowell @danfox01 so I just looked into this and it appears to be in the master branch and integration. Works in test and prod. Is this still an issue or can we close this?

**Comment by danfox01** [comment]
@tmccoy529 functionally this looks good. Can't speak to @martypowell's comment about an issue with scss. Marty if you can confirm, yes this is good to close.

**Comment by martypowell** [comment]
@danfox01 looks ok, and since it was a while ago, we can close and reopen if needed.
