### ISSUE TITLE
Featured event feed isn't honoring max events attribute

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#540]
Oddly, this only appears to be happening on this page: https://www.bcpl.info/_style-library/index.html

The widget is supposed to display 3 events by default, which other values set by the `results-to-display` attribute. For some reason, on this page, that value doesn't have an effect, and events are overflowing the page.

More documentation on this feature: https://github.com/baltimorecounty/BCPL-assets/blob/integration/js/featured-events-widget.md

**Comment by martypowell** [comment]
@danfox01 this is working as expected. If you take a look at the source it reads as follows:

![image](https://user-images.githubusercontent.com/1933400/42032363-585a14f0-7aa7-11e8-85e6-0e9a4bbf5257.png)

I would would like we can update that page to show 4?

**Comment by danfox01** [comment]
Did you adjust anything? It does look OK now, but this is how it appeared yesterday:

![fireshot capture 096 - _sample - https___www bcpl info__style-library_index html](https://user-images.githubusercontent.com/13049389/42032891-0785d9a4-7aa9-11e8-9e6b-9f896cf25475.png)

**Comment by danfox01** [comment]
@martypowell you can see this bug in action right now -- 6 events are showing instead of the set value of 3, and they're overflowing the content area: https://www.bcpl.info/_style-library/index.html

**Comment by martypowell** [comment]
Still can't see it.

![image](https://user-images.githubusercontent.com/1933400/42124515-dd80cad0-7c31-11e8-967c-190a6077604b.png)

On Monday first thing, let's take a look at this.

**Comment by martypowell** [comment]
closing in favor of #541
