### ISSUE TITLE
BCPL Careers styling

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#542]
Dropdown menus have the same height as the text inputs? See the first screen of the "Create Account" page for an example.

**Comment by martypowell** [comment]
This is for Cyber Recruiter. Example page is [here](https://libcyber01p.bcpl.lib.md.us/careers/AppSelfService.aspx?adata=EFnTlvRNZ0v1UddZ5vVXTn%2fybp4Q1KjOKrZ9kRJpTp54%2bYPb%2b%2bIv7S5fXY%2bvAMkoe9h1UW8CnN7MmqajqHT9ikbAAiaT12m7AJGYQ9jNh8jAunWbNUsjf%2fcXVn%2fsElt5Un3VH8zrGJhb6iTah0Kui1c1O9R8fIxMYotFCwAdHqVsC8kBNbcIrkLCjQj%2fY%2fteEfcZxwyMS3G%2fS2SxfAnbbMEx3KzPdlM8ba%2fA0Fa8oj6QY5nHYl3nMqmhozLyLDbhCmxFMScRIxdUWzZcpgRI%2bJqmybXY%2bWhHF9VEwYvNTti%2fLFkbnrSfx9JLq4MI8%2beDK33zF3AiHK2ObiOe3usVAameWjyJfc6LKQDgcxNkAhRyj%2fJ3GDBHNJKKa84pVtO%2fhg%3d%3d)

**Comment by martypowell** [comment]
![image](https://user-images.githubusercontent.com/1933400/42452697-ccec0f4e-8358-11e8-99bf-516258a2e76e.png)

**Comment by jsmith176** [comment]
@danfox01 this is ready to be looked at.

**Comment by danfox01** [comment]
Looks good!. Thanks.
