### ISSUE TITLE
When opening multiple accordions, panels should stay open until closed by the user

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#543]
We would like for accordion panels on the BCPL site to remain open even when another panel is opened. Currently, opening a second panel automatically closes the first one.

I believe this can be accomplished by simply removing the "dataparent" attribute from the panels. Tested in dev, this appears to work find, but @martypowell can you please confirm that this is kosher?

- Docs: https://getbootstrap.com/docs/3.3/javascript/#collapse-options
- In dev: https://dev.bcpl.info/youth/storyville.html

**Comment by martypowell** [comment]
@danfox01 you are correct, do you want/need us to do anything?

**Comment by danfox01** [comment]
@martypowell not right now. I will need a dev to  update the Accordionater to allow for this when generating new markup -- I will log a separate issue.

Will assign this markup changes in SE to my team.

**Comment by danfox01** [comment]
@theilman7, do you have time to work on this one? We just need to remove the "data-parent" attribute from our accordions on BCPL... probably 10-ish pages or so. I will fill you in outside of this thread.

**Comment by theilman7** [comment]
@danfox01 I can do that. I'll keep an eye out for the follow up regarding which pages, and any other info there is.

Thank you!
_Travis

**Comment by danfox01** [comment]
Resolved by markup changes.
