### ISSUE TITLE
Add border to accordions

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#545]
Now that multiple accordions can be open at once, it makes sense to wrap them in some kind of visual container. Can we please add a border of 1px #ebebeb as shown in Sam's mockup below? 

![screen shot 2018-07-10 at 8 17 33 am](https://user-images.githubusercontent.com/13049389/42510809-10e55a8c-841e-11e8-8ea9-f11ceed677f2.png)

@sdurphy FYI

**Comment by martypowell** [comment]
@danfox01 @sdurphy do we want any bottom margin on these?

**Comment by danfox01** [comment]
resolved by 1.5.5
