### ISSUE TITLE
Add additional margin to gray buttons

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#549]
@jsmith176 In #548, we added additional margin to buttons but forgot about another button style. Can you please update? I believe we need to add margin-bottom: `30px` to `btn-default` and `seButton`. You can see the issue here: https://www.bcpl.info/_style-library/index.html#form

@sdurphy can provide more detail if needed. Thanks!

**Comment by jsmith176** [comment]
@danfox01 can do!

**Comment by jsmith176** [comment]
@sdurphy there are no bottom margins currently in [dev](https://dev.bcpl.info/_style-library/index.html#form). Before I change anything, do we know that we want the 30px bottom margin?

**Comment by sdurphy** [comment]
Sorry for the delay... it looks like the margin-bottom for btn-default should be 2 em.

**Comment by jsmith176** [comment]
@sdurphy @danfox01 this is in [dev](https://dev.bcpl.info/_style-library/index.html#form) and is ready for testing.

**Comment by sdurphy** [comment]
Looks good to me! Thanks @jsmith176

**Comment by jsmith176** [comment]
Can do! I'll start working on this now.

**Comment by jsmith176** [comment]
@sdurphy I merged the lastest changes into the master branch.
I moved the changes into dev just in case you want to check them out first.

The following files need to be moved into SE:
- dist/css/master.min.css
- dist/css/master-high-contrast.min.css

@martypowell may need to check on this when he is back in case I missed a step.

**Comment by danfox01** [comment]
Thanks @jsmith176!

**Comment by danfox01** [comment]
@sdurphy did this get deployed to SE?

**Comment by sdurphy** [comment]
@danfox01 I didn't replace these files in prod yet. I can today

**Comment by sdurphy** [comment]
@jsmith176 just confirming... should I take the files from tis location? (master branch): https://github.com/baltimorecounty/BCPL-assets/tree/master/dist/css

**Comment by jsmith176** [comment]
That's the one!

**Comment by sdurphy** [comment]
ok. thanks @jsmith176

**Comment by sdurphy** [comment]
@jsmith176, @danfox01, this has been deployed to prod.

**Comment by martypowell** [comment]
@danfox01 can this be closed?

**Comment by martypowell** [comment]
@jsmith176 can you please add release notes for this hotfix.

**Comment by jsmith176** [comment]
Release notes have been added.
