### ISSUE TITLE
Callout boxes need 1em of top padding

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#555]
Minor change: `.page-callout` doesn't have any top padding. I added it in the head section of this page as a quick fix, but we'll need to update site CSS at some point:

https://www.bcpl.info/services/wireless-printing.html

**Comment by jsmith176** [comment]
@danfox01 are there any other pages with a `.page-callout`? I've made the change but the wireless printing page does not have a layout in dev.

**Comment by danfox01** [comment]
Sorry @jsmith176, just saw this. This is only on that page for now, and it's new so it's not in dev. We copy down again on Tuesday if you just want to wait till then.

**Comment by jsmith176** [comment]
@danfox01 No problem, I did a test on the styles page and it looks pretty good.

![image](https://user-images.githubusercontent.com/2495453/43077033-3e859d4a-8e54-11e8-8268-4e8a5271b567.png)

**Comment by danfox01** [comment]
@jsmith176, the screen shot above looks great. We refreshed dev today if you want to put it in place on that WiFi page. We just need to wipe out the head section styles on that page first.

@sdurphy, looking at the callout style together with the success and error styles... do you think they should all have the same padding?

**Comment by jsmith176** [comment]
@danfox01 do you want this is now as a hotfix?

**Comment by danfox01** [comment]
It's not pressing. As far as I'm concerned it can wait until the next release, unless you'd rather just get it in now.

**Comment by danfox01** [comment]
This one is still pending release, right @jsmith176 ?

**Comment by jsmith176** [comment]
Yep! This is ready to go.

**Comment by martypowell** [comment]
confirmed by @danfox01  and @martypowell, here https://www.bcpl.info/services/wireless-printing.html
