### ISSUE TITLE
Polaris alert banner doesn't show proper color for emergency alert types

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#556]
In both SE and Polaris, banners are supposed to be gold by default but purple if one of the two "emergency" alert types are selected. We posted an emergency alert type this week that showed as purple in SE but yellow in Polaris.

My theory is that when we updated the code to interpret alerts from structured content we didn't update Polaris to do the same.

**Comment by martypowell** [comment]
@danfox01 this code is now in production. It was not integrated, when I get a chance I'll reconcile the dev and production branches.

**Comment by danfox01** [comment]
Thanks @martypowell. Let me know if you want to leave this open until that is complete.

**Comment by martypowell** [comment]
@danfox01  please leave open, until confirmed.

**Comment by martypowell** [comment]
@danfox01 this has been integrated
