### ISSUE TITLE
Homepage events feed showing more than 4 events

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#557]
The homepage feed is supposed to only show four events. I confirmed it contains an attribute of `results-to-display="4"`, however it's currently showing 5 events. (See screenshot.) Not sure why it's doing that now and has never done it in the past.

I assume it's related to #541, but a bigger deal becase it's the home page.

![fireshot capture 102 - baltimore county public library home - https___www bcpl info_index html](https://user-images.githubusercontent.com/13049389/43155877-9103ecaa-8f46-11e8-91cb-0e70e0226f95.png)

**Comment by danfox01** [comment]
This issue seems to occur when one of the featured events is currently in progress. In the screen shot above, "Developer in Residence" was currently underway. When I removed the event from this list, the display went back down to four. I have confirmed this behavior on a few of the branch pages as well with other events.

**Comment by martypowell** [comment]
we will be looking into this tomorrow at 1pm.

**Comment by danfox01** [comment]
Resolved in 1.5.9
