### ISSUE TITLE
Events page intermittently fails to render any events

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#560]
Console shows this error... appears related to the date picker. Doesn't happen every time, but it's fairly often.

```
angular.min.js:124 TypeError: Cannot read property '_flatpickr' of undefined
    at EventsPageCtrl.vm.filterEvents (app.js?version=1.5.2:1076)
    at updateResultsBasedOnFilters (app.js?version=1.5.2:1467)
    at app.js?version=1.5.2:1477
    at app.js?version=1.5.2:1439
    at filterDataSuccessHandler (app.js?version=1.5.2:1412)
    at app.js?version=1.5.2:1435
    at angular.min.js:137
    at m.$digest (angular.min.js:148)
    at m.$apply (angular.min.js:151)
    at l (angular.min.js:103) "Possibly unhandled rejection: {}"
```

@jsmith176 or @tmccoy529 can you please investigate?

**Comment by jsmith176** [comment]
I'll investigate.

**Comment by jsmith176** [comment]
@danfox01 @sdurphy I'll need to log in to SE to test this one.

**Comment by sdurphy** [comment]
@jsmith176, you should be able to log into dev now. Let me know if you have any issues.

**Comment by jsmith176** [comment]
I'm in, thank!

**Comment by jsmith176** [comment]
FYI: Still investigating this. Seems like sometimes the event results return before the date picker element is loaded on the page.

**Comment by martypowell** [comment]
@jsmith176 i think this is right, this had been a problem mike and worked on before

**Comment by jsmith176** [comment]
@danfox01 this is in dev and is ready for testing.

**Comment by danfox01** [comment]
Thanks @jsmith176! @jdomasky can you please run this through the events test plan?

**Comment by jdomasky** [comment]
Yes, I'll test this in dev on August 14 and report back here.

**Comment by jdomasky** [comment]
@danfox01 The Events interface in dev fully passed the Events Test Plan.

**Comment by danfox01** [comment]
Thanks @jdomasky!

@jsmith176 and @martypowell -- this is good to go whenever you're ready. I'd like to get it out this week but if you want to wait a day or two and see what else we can include in this release, that's fine with me.

**Comment by martypowell** [comment]
this was implemented as a hotfix this week.

**Comment by danfox01** [comment]
Thanks guys!

**Comment by danfox01** [comment]
Observed this error again this morning and this afternoon.

**Comment by martypowell** [comment]
@danfox01 still not fixed in dev. I will take another look when I get a chance.

**Comment by martypowell** [comment]
@danfox01 this is a duplicate of #281
