### ISSUE TITLE
Polaris "Return to List" button should return the user to their position to a specific position in search results

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#563]
This is a feature in vanilla Polaris that it seems we might have borked with our styling.

Basically, the user's position on the search page is supposed to be retained when they navigate between the search results and individual records. That's not happening right now.

**To replicate:** 

- Perform a search of the BCPL catalog
- Choose any item from the search results and click through to that record.
- Note the URL contains &pos=# corresponding to the item's place in the list.
- Click "Return to List"
- The user is taken to the top of the list, even though the URL now contains &pos=#

This is a low priority issue depending on effort to fix, but I'd like to at least triage it now.

**Comment by martypowell** [comment]
appears to be a javascript error

```Uncaught TypeError: Cannot read property 'offsetTop' of null```

![image](https://user-images.githubusercontent.com/1933400/44035221-fd9825a2-9edc-11e8-9cbe-2b4f385acc5f.png)

**Comment by danfox01** [comment]
Released in 1.5.9
