### ISSUE TITLE
[DEV] Content page and hub page cards exploded

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#576]
Probably resulting from the blog card tweaks last week.

https://dev.bcpl.info/books-and-more/
https://dev.bcpl.info/books-and-more/cisco-networking-academy.html

**Comment by martypowell** [comment]
💥

**Comment by martypowell** [comment]
@danfox01 this is ready for another look in dev. The issue here is some generic looking css, that was actually a bit more specific than first expected

**Comment by danfox01** [comment]
Looks good. Thanks Marty.
