### ISSUE TITLE
Add subheads to homepage promoters

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#588]
To make promoters more explanatory and actionable, we need to add subheads to the cards. I'm thinking something like this mockup. @sdurphy let me know what you think. A few requirements:

- Subheadings will be 1 or 2 lines
- Regardless of number of lines, all cards should size to the height of the tallest card.
- All other card behaviors (e.g., hover states) should stay the same.

![fireshot capture 120 - baltimore county public library home - https___www bcpl info_index html](https://user-images.githubusercontent.com/13049389/45118910-daf30280-b127-11e8-9691-af1f0c0399d4.png)

**Comment by jsmith176** [comment]
@danfox01 can we publish those subheads to dev? I attempted to make the changes myself in site exec but I didn't want to publish them without the go-ahead.

**Comment by danfox01** [comment]
@jsmith176 if you're asking if it's ok for you to publish in dev, please feel free. If I misunderstood your question please let me know.

**Comment by danfox01** [comment]
Looks good! We just need to accommodate responsive breakpoints. I'm thinking:
- Md and lg screens are good as-is.
- Sm screens should display as 2x2 boxes (similar to current display in prod)
- Xs should display as rectangles (see below)

@sdurphy, do you have any specific thoughts?

![fireshot capture 128 - baltimore county public library home - https___dev bcpl info_index html](https://user-images.githubusercontent.com/13049389/45643772-d9133280-ba89-11e8-8622-dea2f7673f51.png)

**Comment by jsmith176** [comment]
@danfox01 changes are in dev. @martypowell thinks the spacing between the cards on xs screens is too large. Would you like me to make them smaller?

**Comment by danfox01** [comment]
Looks great! Just a couple things:

-  I agree we could use a bit less space at XS. I'd like to hear what Sam says. @sdurphy do you have a recommendation?
-  Unfortunately object-fit is not supported by IE11, which is still 30% of BCPL's traffic. Is there another way of achieving the image sizing, or a polyfill for IE11? (I do like the idea of using that property -- I can think of a few other places we could use it as well.)

**Comment by jsmith176** [comment]
@danfox01 I wasn't able to get the images to crop properly but all of the other changes are in dev now.

**Comment by jsmith176** [comment]
__Changes__
- Adjustments to css for feature subheads
- Added a horizontal rule and subhead text to each feature in SE
- Added the _flex_ class to the columns and container row in SE
- Added the _flex-wrap_ class to the container row in SE
- Wrapped subhead text in div element

_SE changes are for BCPL/\_inclusions/homepage/component-features._
_Changes can be viewed in [dev](dev.bcpl.info)_

**Comment by martypowell** [comment]
@danfox01 what is going on with this?

**Comment by danfox01** [comment]
@martypowell, I'm not sure I ever reviewed the final version of this and it looks like it's not longer in dev. Once it is in place, I'll need to take a few screen shots to show BCPL before we go live. it can wait till I get back if that's easiest.

**Comment by tmccoy529** [comment]
@danfox01 @martypowell based on what I'm seeing this code is already out in prod and can be created if you follow this template adding those css classes to the parent row and each column (card):
```html
 <div class="row flex flex-column-md flex-wrap">
          <div class="col-md-3 col-sm-6 col-xs-6 flex flex-column">
                   <a class="feature" href="https://www.bcpl.info/services/technology-for-loan.html">
                        <div class="feature-image-wrapper"><img src="/sebin/l/m/promotion-teen-writing.jpg" alt="Teen Writing Contest"></div>
                                 <p>Teen Writing Contest</p>
                                 <hr>
                                 <div>Extra text for Teen Image</div> 
                   </a>
                         </div>
```
Changes would be made to  BCPL/_inclusions/homepage/component-features in SE

**Comment by danfox01** [comment]
@tmccoy529 Perfect, thanks for sleuthing this out. I two changes small to your markup example above:

- Removed `flex-column-md` because I think it's causing an issue with flex at tablet size. Removing it seems to do the trick. 
- Changed the final text element from `<div> `to `<p>` for semantics

**Comment by sdurphy** [comment]
Can we replace the <hr> with a </br>? 
![screen shot 2019-02-19 at 3 24 36 pm](https://user-images.githubusercontent.com/2189638/53045241-16c22000-345b-11e9-8e18-b3951b22c2ae.png)

**Comment by danfox01** [comment]
@sdurphy yes. For now we can replace the` <hr>` with a `<br>` in the markup. The better solution is a CSS margin. I'll log that separately.

**Comment by tmccoy529** [comment]
@danfox01 looks good, I like it. The last release was on 1/28 which was a month after this code was pushed into Master so this should be in Prod already. I guess once that's verified we can probably close this one out?

**Comment by danfox01** [comment]
Hmm... need to look a little further but it looks like this might not be in prod after all.

**Comment by martypowell** [comment]
@danfox01 what's going on with this?

**Comment by danfox01** [comment]
@martypowell, just confirmed this is not in prod. Here's a test page showing the same markup that's in dev, but you can see the styling isn't in place: https://www.bcpl.info/_test/index-test.html

**Comment by martypowell** [comment]
@danfox01 changes are in production.

**Comment by danfox01** [comment]
Confirmed. Thanks guys.
