### ISSUE TITLE
Reconcile recent Polaris prod changes with source control.

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#595]
@martypowell I know you wanted to address the BCPL emergency alert color issue here. I also recently updated the BCPL nav directly to site.master in prod, which will need to be reconciled as well.

**Comment by martypowell** [comment]
@danfox01 the code is in good shape, if you want to add the release notes please feel free, but i don't have a recollection of what happened when (yes i know ive been slacking)
