### ISSUE TITLE
Jobs Tool: Add space around text in table cells

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#596]
https://libcyber01p.bcpl.lib.md.us/Careers/

Mockup:
![2018-09-25](https://user-images.githubusercontent.com/13049389/46018263-7c2a0480-c0a7-11e8-909d-3db21908bc05.png)

**Comment by martypowell** [comment]
@danfox01 i sent this to steve g, i need to reconcile this with source control, so let's keep this open for now.
