### ISSUE TITLE
Events: "Back to List" button should behave as browser back

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#608]
When viewing an event's details, the browser back button is currently a static link to the main events page. This is frustrating to some users because they lose their filters.

Ideally, this button should behave like  browser back to retain the filters. See the blog as an example: https://www.bcpl.info/blog/2018/farewell-to-a-sesame-street-friend.

**Comment by martypowell** [comment]
@danfox01 this is production

**Comment by danfox01** [comment]
Confirmed. Thanks!
