### ISSUE TITLE
Swagger documentation updates for services.bcpl.info

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#609]
Three things may need to be updated, I think. Let me know your thoughts, @martypowell .

- I believe that [this endpoint](https://services.bcpl.info/swagger/ui/index#!/Search/SearchTerm_Get) is used for the autocomplete. Can you confirm that, and if so -- does it make sense for us to identify that in the endpoint description?

- The Swiftype endpoints ([this](https://services.bcpl.info/swagger/ui/index#!/Search/SiteSearch_Get) and [this](https://services.bcpl.info/swagger/ui/index#!/Search/SiteSearch_TrackClickThrough)) are no longer in use. How should we handle? Remove entirely, mark as depricated, etc?

- The[ Get Carousel](https://services.bcpl.info/swagger/ui/index#!/Carousel/Carousel_Get) endpoint description is incomplete. I think it should say "Get a list of books or other materials from a Polaris record set."

**Comment by martypowell** [comment]
@danfox01 

- it is used for autocomplete, but the swagger docs, should not reflect how we are using the data we are consuming, just what the endpoint provides
- I removed this code, and submitted for code review. I left the part of the code that specified how the search should work aka endpoints, so that we can reuse if needed
- Description updated and submitted for code review

**Comment by danfox01** [comment]
Great, thanks @martypowell. Keep me posted on next steps after review.

**Comment by danfox01** [comment]
@martypowell and @tmccoy529, this is an old update to our Swagger documentation that was last updated in Nov pending code review. Does it make sense to try to pack these updates with any changes we're making to services for BCPL event sorting fix? (#615)

**Comment by danfox01** [comment]
@danfox01 will verify docs in testservices

**Comment by danfox01** [comment]
@martypowell @tmccoy529, looks like these did not make it to testservices. Let me know if you need me to summarize the changes that need to occur since it's been awhile since the issue was first logged.

**Comment by tmccoy529** [comment]
@danfox01 I'll take a look and update when its complete.

**Comment by tmccoy529** [comment]
@danfox01 I'm looking into this and all the changes to the original issue seem to have been resolved. Are there any other endpoints you feel don't have good enough descriptions? The alerts notification is listed as this "Get the highest ranked alert to display in banner from bcpl.info". Everything else to me looks like its resolved but wanted to check with you before I move this into the ready to release tab.

**Comment by danfox01** [comment]
@tmccoy529 this looks good to me. One minor grammar change for `/api/structured-content/blog` should be "its" not "it's".

Otherwise, it's great. @martypowell can take a quick look too?

**Comment by martypowell** [comment]
looks good to me, there is a small error at the bottom of the page, I would look into maybe what that is displaying.

![image](https://user-images.githubusercontent.com/1933400/52859241-30313800-30fa-11e9-8b04-2be0fee17f6f.png)

@danfox01 @tmccoy529

**Comment by tmccoy529** [comment]
@danfox01 @martypowell I'll fix the grammar issue and look into that error.

**Comment by danfox01** [comment]
@tmccoy529 will check with @martypowell

**Comment by danfox01** [comment]
Per @martypowell: this is good for release. I'll add a separate issue to look into the error more, but let's not hold up the other stuff.

**Comment by martypowell** [comment]
@danfox01 i think this is in prod?

**Comment by danfox01** [comment]
@danfox01 confirmed in prod. Thanks!
