### ISSUE TITLE
Reconcile BCPL releases

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#611]
Last release documented here is 1.5.9 on Aug 22. I believe 1.6 included blog enhancements and Google and the switch search. @martypowell, let's get together to confirm that and I can create the release.

**Comment by martypowell** [comment]
Includes #601, #602, #603, #604

**Comment by danfox01** [comment]
Reconciled BCPL release 1.6 and React-Blog 1.0:

- https://github.com/baltimorecounty/react-blog/releases/tag/1.0.0
- https://github.com/baltimorecounty/BCPL-assets/releases/tag/1.6
