### ISSUE TITLE
Was react blog merged to master?

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#612]
@martypowell , per your question about this feature. Please investigate an update as needed.

https://github.com/baltimorecounty/react-blog

**Comment by martypowell** [comment]
@danfox01 confirmed master and integration are in sync. added [release notes](https://github.com/baltimorecounty/react-blog/releases/tag/1.0.0) for the initial release

**Comment by danfox01** [comment]
Thanks!
