### ISSUE TITLE
Contact forms on locations page do not render in IE11

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#621]
https://www.bcpl.info/locations/index.html

**Current behavior:**
In IE11, selecting the "Contact" link on any branch card simply scrolls the page to the top.

**Expected behavior:**
Selecting the Contact link should spawn a modal window with a LibAnswers contact form.

I think the going theory is that this might never have worked, which is possible, but I would be surprised if that's the case. This feature has been on the locations test plan since we went live -- it would have been a major oversight if it failed and we didn't realize it. Entirely possible, but unlikely.

**Comment by danfox01** [comment]
@martypowell your changes in dev look good. @jdomasky noted that every time a location contact modal spawns, the page scrolls back to the top which is annoying. Is it possible to keep the user's position?

**Comment by martypowell** [comment]
@danfox01 yes, it's in dev. @tmccoy529 i did this during lunch, let's review monday morning

**Comment by tmccoy529** [comment]
This issue is no longer valid since we dont support IE11 any longer
