### ISSUE TITLE
Swiftype search API is showing new queries, and shouldn't be

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#624]
I received a summary report from Swiftype this morning that suggests we sent about 300 search queries via their API in the past week.

Swiftype was removed from the site and replaced with Google Custom Search a few months ago, so there should be no traffic. I'm assuming there must have been a regression in the latest change (1.6.3).

**Comment by martypowell** [comment]
@danfox01 hopefully this will be resolved when we push the #621 I removed any references to swiftype

**Comment by danfox01** [comment]
Resolved in HF 1.6.8. Confirmed via Swiftype admin dashboard -- no longer showing search traffic.
