### ISSUE TITLE
Remove additional space for CyberRecruiter job application form

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#625]
BCPL has requested that the empty space at the top the application form be removed. [See an example here.](https://jobs.bcpl.info/Careers/AppSelfService.aspx?adata=EA%2fv9SYA1SnggUqoY4rvTAvYnQ0x%2fTkYyPERVBaimDNPFzgofyuE5%2fkAjHxp7Gj7zorQ4PXLNrSpyG0CLXL2HNmqebtCspKBZJy5Rs0wAQrOAnzn43n74nmCFDdDpglrW8b126MNfcS8EO0wEoJxh2KAtK5INahvK7T%2fr4dQynTvc7J1vCPOTW%2fbJlHCtRLh6XlWaAP49egeQOMMJsxRgJp%2bHgvz48MRqxpy3VN%2fMjCT58cpdvY2H0rCaSmdC7HDf1Y7R4AuZt6YY7uUQXRQHxWfd0nG2ll%2bmZPpXLY2XKXcgRkU1NCJw%2fruEwU4A4nBt0%2bPOtzCBXuRbRcrevMelnje9X4LNKPy3WakVXWFd03V)

I believe this is coming from block styling we added for form fields, which is being inherited by hidden form fields here. Adding **display:none** to the containing element may do the trick, but it needs to be specific enough not to hide other necessary fields. We also need to verify that applying **display:none** to a hidden field will still allow that field to submit.

**Comment by martypowell** [comment]
@danfox01 understood, I believe with josh leaving, this code might be out of date in source control as well.

**Comment by danfox01** [comment]
@martypowell @tmccoy529 Can one of you gentlemen look into this. There is a SolveIT ticket too -- not sure the #, it's from December. Minor issue but the customer is asking status.

**Comment by danfox01** [comment]
@martypowell @tmccoy529 , I know you guys have been looking at this and we have other things cooking. Can you please provide an ETA on a fix? This is low priority for me but I'm getting hounded.

**Comment by tmccoy529** [comment]
@danfox01 Its an easy enough fix. Basically the hidden text boxes have a style of visibility : hidden which renders the control but just hides the actual element showing white space. Ive changed it to display: none which still allows you to interact with the elements but doesn't render them. However, I'm working with Steve to grant me access to push this out to be tested. By noon today I should have it ready to test if not earlier.

**Comment by tmccoy529** [comment]
@danfox01 I have pushed out the fix to dev after flailing around like a fish out of water. You can [see an example here](https://libcyber01d.bcpl.lib.md.us/Careers/AppSelfService.aspx?adata=EKwnbznXu6RSGCgDTMPJhCA232K9kONwyzuuoxBxCo60umH5ZHlr82zzwFawV8kgpVxhTaEaTdmt%2fMAc77fQ0GPB4Pgge17ogSLJKs76akX26am2sLJPp7mUmlkwx%2ffh8RPJfuZBipJhYQDZHkYHIzPT1ivFjJb78y%2bO%2fUNWltXgGAAbsUvCzyWwF5XCklTpMFeD9cyaAmUxTzwQQVLv2HswpvDCcJjF09Az%2b2ZFuXARumbw%2f0pWNuysGwIYmuotfzspBxoiF3D%2fjEoSYUOcHpyZId1DPX4xREweXpd%2buriZ8rcfTvK8I2YFjgoFzGWdoWfwZGCVBG6Aj99p6W4x0CkbSf68m1sKfIwOd%2fNyMAOt)

**Comment by danfox01** [comment]
@tmccoy529 this looks good, thank you. We can release this as a HF whenever you are ready. I'm not sure of the process for this one -- probably will need NSU for file replacement similar to how we handle Polaris.

**Comment by tmccoy529** [comment]
@danfox01 The hot fix was just done. Can you please verify this is complete?

**Comment by danfox01** [comment]
This looks good! There is currently a performance issue with this app in prod but that existed before the HF, so I'm sure it's unrelated.

**Comment by martypowell** [comment]
@danfox01 yes i would bet a dime this is not related.
