### ISSUE TITLE
Catalog autocomplete doesn't work.

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#629]
After release 1.6.6, the catalog autocomplete no longer renders.

**Expected functionality:**
Select "Search" button from any page and begin typing into the box. Autocomplete should populate matching titles from Polaris.

**Current functionality:**
Select "Search" button from any page on bcpl.info and begin typing into the box. No autocomplete terms are suggested.

FYI @jdomasky

**Comment by martypowell** [comment]
@danfox01 hotfix implemented, code review submitted

**Comment by danfox01** [comment]
Thanks @martypowell. Verified in prod.
