### ISSUE TITLE
Notary Services link broken in Polaris nav

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#636]
1. Got to https://catalog.bcpl.lib.md.us/polaris/
2. Select Services > Notary Services

Note that the link is broken. It should point to https://www.bcpl.info/services/notary.html. Has probably been like this and unnoticed for a few months.

I believe this requires an update to the master page in Polaris.

**Comment by danfox01** [comment]
@tmccoy529 or @sgrg1 -- this one should be pretty simple. Just a basic markup change and updating source control before sending along to the server team to replace the file. Can either of you tackle tomorrow?

**Comment by tmccoy529** [comment]
@danfox01 Sanjay and I are looking into this now.

**Comment by martypowell** [comment]
@tmccoy529 shoot an email to Mike Kollin and ask him for the latest copy of Site.Master, you should be able to fix it in that. Source control is out of date with the production file because we needed to get something in quick.

@sgrg1 @danfox01

**Comment by tmccoy529** [comment]
@danfox01 this has been moved over to test for review.

**Comment by danfox01** [comment]
@tmccoy529, this looks good to move to prod. Will you use this opportunity to get the Polaris source control up to date in TFS, or should I log a separate issue for that?

**Comment by tmccoy529** [comment]
@danfox01 @martypowell I went ahead and loaded the prod version into source along with this fix. Probably should have been a separate issue but its all done now in one PR so once Marty gets back we can finalize that.

**Comment by danfox01** [comment]
Thanks! This is in prod.
