### ISSUE TITLE
[DEV] BCPL dev does not render any JS

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#665]
**Describe the bug**
JS is not rendering correctly on dev.bcpl.info. This is probably related to the constants change ealier this year -- its tarted occuring then but we didn't have bandwidth to address it. It appears to occur sitewide.

Normally a dev issue wouldn't be a huge priority but we're going to start the SE upgrade soon, and we need dev mirroring prod before we get started.

**To Reproduce**
1. Go to dev.bcpl.info 
2. Note that all JS-dependent functions do not render correctly (e.g., carousel, hamburger nav, book feed)

**Expected behavior**
All dynamic functions to render as they do in production.

**Affected device and browser:**
 - All

**Comment by tmccoy529** [comment]
this appears to have been fixed
